CMFD_HSD_FORMAT_IDS = {
    HSD = 0,
    DL = 1,
    DCTL = 2,
    ROUTE = 3
}

CMFD_HSD_DL_IDS = {
    ALL = 0,
    FORM = 1,
    TGT = 2,
    NONE = 3
}

CMFD_HSD_DL_IDS.ALL = "DL\nALL"
CMFD_HSD_DL_IDS.FORM = "DL\nFORM"
CMFD_HSD_DL_IDS.TGT = "DL\nTGT"
CMFD_HSD_DL_IDS.NONE = "DL\nNONE"