CMFD_DVR_FORMAT_IDS = {
    DVR       = 0,
    PLBCK      = 1,
}

CMFD_DVR_STATE_IDS = {
    FAIL = 0,
    DOOR = 1,
    NO_TAPE = 2,
    EOT = 3,
    STOP = 4,
    STBY = 5,
    REC = 6,
}

CMFD_DVR_STATE_IDS.FAIL = "FAIL"
CMFD_DVR_STATE_IDS.DOOR= "DOOR"
CMFD_DVR_STATE_IDS.NO_TAPE = "NO TAPE"
CMFD_DVR_STATE_IDS.EOT = "EOT"
CMFD_DVR_STATE_IDS.STOP = "STOP"
CMFD_DVR_STATE_IDS.STBY = "STBY"
CMFD_DVR_STATE_IDS.REC = "REC"

CMFD_DVR_MODE_IDS = {
    AUTO = 0,
    MAN = 1,
}

CMFD_DVR_MODE_IDS.AUTO = "AUTO"
CMFD_DVR_MODE_IDS.MAN = "MAN"

CMFD_DVR_REC_IDS = {
    NO_CYCLE = 0,
    CYCLE = 1,
}

CMFD_DVR_SOURCE_IDS = {
    HUD = 0,
    FWD_LCMFD = 1,
    FWD_RCMFD = 2,
    AFT_LCMFD = 3,
    AFT_RCMFD = 4,
    FLIR = 5,
}