
UFCP_NAV_MODE = get_param_handle("UFCP_NAV_MODE")
UFCP_NAV_TIME = get_param_handle("UFCP_NAV_TIME")
UFCP_VAH = get_param_handle("UFCP_VAH")
UFCP_VV = get_param_handle("UFCP_VV")

UFCP_FORMAT_IDS = {
    MAIN = 0,
    WPT = 1,
    MENU = 2,
    NAV_MODE = 3,
    NAV_MISC = 4,
    VVVAH = 5,
}

UFCP_MAIN_SEL_IDS = {
    FYT = 0,
}

UFCP_VVVAH_MODE_IDS = {
    VAH = 0,
    OFF = 1,
    VV_VAH = 2,
}

UFCP_NAV_MODE_IDS = {
    MAN = 0,
    AUTO = 1,
    END = 2,
}

UFCP_NAV_TIME_IDS = {
    ETA = 0,
    TTD = 1,
    DT = 2,
    END = 3,
}

UFCP_NAV_SOLUTION_IDS = {
    NAV_EGI = 0,
    NAV_INS = 1,
    NAV_GPS = 2,
    NAV_BU  = 3,
}
UFCP_NAV_SOLUTION_IDS[UFCP_NAV_SOLUTION_IDS.NAV_EGI] = "NAV-EGI"
UFCP_NAV_SOLUTION_IDS[UFCP_NAV_SOLUTION_IDS.NAV_INS] = "NAV-INS"
UFCP_NAV_SOLUTION_IDS[UFCP_NAV_SOLUTION_IDS.NAV_GPS] = "NAV-GPS"
UFCP_NAV_SOLUTION_IDS[UFCP_NAV_SOLUTION_IDS.NAV_BU] = "NAV-B/U"

UFCP_TIME_TYPE_IDS = {
    LC = 0,
    RT = 1,
    SW = 2.
}
UFCP_TIME_TYPE_IDS[UFCP_TIME_TYPE_IDS.LC] = "LC"
UFCP_TIME_TYPE_IDS[UFCP_TIME_TYPE_IDS.RT] = "RT"
UFCP_TIME_TYPE_IDS[UFCP_TIME_TYPE_IDS.SW] = "SW"
