local cockpit = folder.."../../../Cockpit/Scripts/"
dofile(cockpit.."devices.lua")
dofile(cockpit.."command_defs.lua")

local res = external_profile("Config/Input/Aircrafts/common_keyboard_binding.lua")

join(res.keyCommands,{





-- Flight Control               
{combos = {{key = 'Up'}},		                                        down = iCommandPlaneUpStart,			            up = iCommandPlaneUpStop,			        name = _('Aircraft Pitch Down'),	                            category = _('Flight Control')},
{combos = {{key = 'Down'}},		                                        down = iCommandPlaneDownStart,			            up = iCommandPlaneDownStop,			        name = _('Aircraft Pitch Up'),		                            category = _('Flight Control')},
{combos = {{key = 'Left'}},		                                        down = iCommandPlaneLeftStart,			            up = iCommandPlaneLeftStop,			        name = _('Aircraft Bank Left'),		                            category = _('Flight Control')},
{combos = {{key = 'Right'}},	                                        down = iCommandPlaneRightStart,			            up = iCommandPlaneRightStop,		        name = _('Aircraft Bank Right'),	                            category = _('Flight Control')},
{combos = {{key = 'Z'}},		                                        down = iCommandPlaneLeftRudderStart,	            up = iCommandPlaneLeftRudderStop,	        name = _('Aircraft Rudder Left'),	                            category = _('Flight Control')},
{combos = {{key = 'X'}},		                                        down = iCommandPlaneRightRudderStart,	            up = iCommandPlaneRightRudderStop,	        name = _('Aircraft Rudder Right'),	                            category = _('Flight Control')},


{combos = {{key = 'Num+'}}, 						                    pressed = iCommandThrottleIncrease,		            up = iCommandThrottleStop,                  name = _('Throttle Up'),		                                category = _('Flight Control')},
{combos = {{key = 'Num-'}}, 						                    pressed = iCommandThrottleDecrease,		            up = iCommandThrottleStop,                  name = _('Throttle Down'),		                                category = _('Flight Control')},
{                            						                    down = Keys.Cutoff,               		            up = Keys.Cutoff,                           name = _('Engine Cutoff else other'),		                    category = _('Flight Control'),                         value_down =  1.0,		value_up = 0.0},

{combos = {{key = 'PageUp'}},							                down = iCommandPlaneAUTIncreaseRegime,	            	                                        name = _('Throttle Step Up'),			                        category = _('Flight Control')},
{combos = {{key = 'PageDown'}},							                down = iCommandPlaneAUTDecreaseRegime,	            	                                        name = _('Throttle Step Down'),			                        category = _('Flight Control')},

{combos = {{key = 'Z', reformers = {'RCtrl'}}},	                        pressed = iCommandPlaneTrimLeftRudder,	            up = iCommandPlaneTrimStop,                 name = _('Trim: Rudder Left'),		                            category = _('Flight Control')},
{combos = {{key = 'X', reformers = {'RCtrl'}}},	                        pressed = iCommandPlaneTrimRightRudder,	            up = iCommandPlaneTrimStop,                 name = _('Trim: Rudder Right'),		                            category = _('Flight Control')},

-- Systems                      
{combos = {{key = 'B'}},							                    down = iCommandPlaneAirBrake,				                                                    name = _('Airbrake'),							                category = _('Systems')},
{combos = {{key = 'B', reformers = {'LShift'}}},	                    down = iCommandPlaneAirBrakeOn,                     up = iCommandPlaneAirBrakeOn,		        name = _('Airbrake On'),						                category = _('Systems'),                        value_down =  1.0,		value_up = 0.0},
{combos = {{key = 'B', reformers = {'LCtrl'}}},		                    down = iCommandPlaneAirBrakeOff,                    up = iCommandPlaneAirBrakeOff,		        name = _('Airbrake Off'),						                category = _('Systems'),                        value_down =  1.0,		value_up = 0.0},
{combos = {{key = 'T'}},							                    down = iCommandPlaneWingtipSmokeOnOff,		                                                    name = _('Smoke'),								                category = _('Systems')},
{combos = {{key = 'L'}},							                    down = iCommandPlaneCockpitIllumination,	                                                    name = _('Illumination Cockpit'),				                category = _('Systems')},
{combos = {{key = 'L', reformers = {'RCtrl'}}},		                    down = iCommandPlaneLightsOnOff,			                                                    name = _('Navigation lights'),					                category = _('Systems')},
{combos = {{key = 'L', reformers = {'RAlt'}}},		                    down = iCommandPlaneHeadLightOnOff,			                                                    name = _('Gear Light Near/Far/Off'),			                category = _('Systems')},
{combos = {{key = 'F'}},							                    down = iCommandPlaneFlaps,					                                                    name = _('Flaps Up/Down'),						                category = _('Systems')},
{combos = {{key = 'F', reformers = {'LShift'}}},	                    down = iCommandPlaneFlapsOn,				                                                    name = _('Flaps Landing Position'),				                category = _('Systems')},
{combos = {{key = 'F', reformers = {'LCtrl'}}},		                    down = iCommandPlaneFlapsOff,				                                                    name = _('Flaps Up'),							                category = _('Systems')},
{combos = {{key = 'G'}},							                    down = iCommandPlaneGear,					                                                    name = _('Landing Gear Up/Down'),				                category = _('Systems')},
{combos = {{key = 'G', reformers = {'LCtrl'}}},		                    down = iCommandPlaneGearUp,					                                                    name = _('Landing Gear Up'),					                category = _('Systems')},
{combos = {{key = 'G', reformers = {'LShift'}}},	                    down = iCommandPlaneGearDown,				                                                    name = _('Landing Gear Down'),					                category = _('Systems')},
{                                                                       down = iCommandPlaneGearUp,					        up = iCommandPlaneGearDown,                 name = _('Landing Gear Down else Up'),		                    category = _('Systems')},
{combos = {{key = 'W'}},							                    down = iCommandPlaneWheelBrakeOn,                   up = iCommandPlaneWheelBrakeOff,            name = _('Wheel Brake On'),	                                    category = _('Systems')},
-- {combos = {{key = 'W',	reformers = {'LCtrl'}}},	                    down = iCommandPlaneWheelBrakeLeftOn,	            up = iCommandPlaneWheelBrakeLeftOff,		name = _('Wheel Brake Left - ON/OFF'),		                    category = {_('Systems')}},
-- {combos = {{key = 'W',	reformers = {'LAlt'}}},		                    down = iCommandPlaneWheelBrakeRightOn,	            up = iCommandPlaneWheelBrakeRightOff,		name = _('Wheel Brake Right - ON/OFF'),		                    category = {_('Systems')}},
{combos = {{key = 'C', reformers = {'LCtrl'}}},		                    down = iCommandPlaneFonar,					                                                    name = _('Canopy Open/Close'),					                category = _('Systems')},
{combos = {{key = 'N', reformers = {'RShift'}}},	                    down = iCommandPlaneResetMasterWarning,		                                                    name = _('Audible Warning Reset'),				                category = _('Systems')},
{                                                                       down = Keys.JettisonWeapons,                        up = Keys.JettisonWeapons,                  name = _('Weapons Jettison'),                                   category = _('Systems'),                        value_down =  1.0,		value_up = 0.0},
{combos = {{key = 'E', reformers = {'LCtrl'}}},		                    down = iCommandPlaneEject,					                                                    name = _('Eject (3 times)'),					                category = _('Systems')},

{combos = {{key = 'H', reformers = {'RCtrl','RShift'}}},                pressed = iCommandHUDBrightnessUp,		                                                        name = _('HUD Brightness up'),					                category = _('Systems')},
{combos = {{key = 'H', reformers = {'RShift','RAlt'}}},                 pressed = iCommandHUDBrightnessDown,	                                                        name = _('HUD Brightness down'),				                category = _('Systems')},

-- {													                    down = iCommandPilotSeatAdjustmentUp,	            up = iCommandPilotSeatAdjustmentStop,		name = _('SEAT ADJ Switch - UP/OFF'),		                    category = {_('Systems')}},
-- {													                    down = iCommandPilotSeatAdjustmentDown,	            up = iCommandPilotSeatAdjustmentStop,		name = _('SEAT ADJ Switch - DOWN/OFF'),		                    category = {_('Systems')}},

{combos = {{key = '=', reformers = {'RShift'}}},                        pressed = iCommandAltimeterPressureIncrease,	    up = iCommandAltimeterPressureStop,         name = _('Altimeter Pressure Increase'),                        category = _('Systems')},
{combos = {{key = '-', reformers = {'RShift'}}},                        pressed = iCommandAltimeterPressureDecrease,        up = iCommandAltimeterPressureStop,         name = _('Altimeter Pressure Decrease'),                        category = _('Systems')},

-- Stick                
{combos = {{key = '.', reformers = {'RCtrl'}}},	                        pressed = iCommandPlaneTrimUp,			            up = iCommandPlaneTrimStop,                 name = _('Trim: Nose Up'),			                            category = {_('Stick'), _('HOTAS')}},
{combos = {{key = ';', reformers = {'RCtrl'}}},	                        pressed = iCommandPlaneTrimDown,		            up = iCommandPlaneTrimStop,                 name = _('Trim: Nose Down'),		                            category = {_('Stick'), _('HOTAS')}},
{combos = {{key = ',', reformers = {'RCtrl'}}},	                        pressed = iCommandPlaneTrimLeft,		            up = iCommandPlaneTrimStop,                 name = _('Trim: Left Wing Down'),	                            category = {_('Stick'), _('HOTAS')}},
{combos = {{key = '/', reformers = {'RCtrl'}}},	                        pressed = iCommandPlaneTrimRight,		            up = iCommandPlaneTrimStop,                 name = _('Trim: Right Wing Down'),	                            category = {_('Stick'), _('HOTAS')}},

{combos = {{key = 'D'}},	                                            down = Keys.StickStep,	                            up = Keys.StickStep,                        name = _('Step'),		                                        category = {_('Stick'), _('HOTAS')},            value_down =  1.0,		value_up = 0.0},
{combos = {{key = 'Enter'}},	                                        down = Keys.StickDesignate,	                        up = Keys.StickDesignate,                   name = _('Designate'),                                          category = {_('Stick'), _('HOTAS')},            value_down =  1.0,		value_up = 0.0},
{combos = {{key = 'Enter', reformers = {'RShift'}}},                    down = Keys.StickUndesignate,	                    up = Keys.StickUndesignate,                 name = _('Undesignate'),	                                    category = {_('Stick'), _('HOTAS')},            value_down =  1.0,		value_up = 0.0},

{combos = {{key = '1'}},                                                down = Keys.MasterModeSw,	                        up = Keys.MasterModeSw,                     name = _('Main Mode Switch - NAV'),                             category = {_('Stick'), _('HOTAS')},            value_down =  1.0,		value_up = 0.0},
{combos = {{key = '2'}},                                                down = Keys.MasterModeSw,	                        up = Keys.MasterModeSw,                     name = _('Main Mode Switch - A/G'),                             category = {_('Stick'), _('HOTAS')},            value_down =  2.0,		value_up = 0.0},
{combos = {{key = '3'}},                                                down = Keys.MasterModeSw,	                        up = Keys.MasterModeSw,                     name = _('Main Mode Switch - A/A INT'),	                        category = {_('Stick'), _('HOTAS')},            value_down =  3.0,		value_up = 0.0},
{combos = {{key = '4'}},                                                down = Keys.MasterModeSw,	                        up = Keys.MasterModeSw,                     name = _('Main Mode Switch - A/A DGFT'),                        category = {_('Stick'), _('HOTAS')},            value_down =  4.0,		value_up = 0.0},

{                                                                       down = Keys.APDisengage,                            up = Keys.APDisengage,                      name = _('Autopilot Disengage'),                                category = {_('Stick'), _('HOTAS')},            value_down =  1.0,		value_up = 0.0},
{                                                                       down = Keys.APOvrd,                                 up = Keys.APOvrd,                           name = _('Autopilot Override'),                                 category = {_('Stick'), _('HOTAS')},            value_down =  1.0,		value_up = 0.0},

{                                                                       down = Keys.Call,	                                up = Keys.Call,                             name = _('Call'),                                               category = {_('Stick'), _('HOTAS')},            value_down =  1.0,		value_up = 0.0},

{                                                                       down = Keys.Trigger,	                            up = Keys.Trigger,                          name = _('Gun Trigger First Detent'),                           category = {_('Stick'), _('HOTAS')},            value_down =  1.0,		value_up = 0.0},
{combos = {{key = 'Space'}},                                            down = Keys.Trigger,	                            up = Keys.Trigger,                          name = _('Gun Trigger Second Detent'),                          category = {_('Stick'), _('HOTAS')},            value_down =  2.0,		value_up = 0.0},
{combos = {{key = 'Space',	reformers = {'RAlt'}}},	                    down = Keys.WeaponRelease,	                        up = Keys.WeaponRelease,	                name = _('Weapon Release Button (WRB)'),                        category = {_('Stick'), _('HOTAS')},            value_down =  1.0,		value_up = 0.0},

{                                                                       down = Keys.DisplayMngt,                            up = Keys.DisplayMngt,                      name = _('DMS Fwd - HUD'),                                      category = {_('Stick'), _('HOTAS')},            value_down =  1.0,		value_up = 0.0},
{                                                                       down = Keys.DisplayMngt,                            up = Keys.DisplayMngt,                      name = _('DMS Aft - No Function'),                              category = {_('Stick'), _('HOTAS')},            value_down =  2.0,		value_up = 0.0},
{                                                                       down = Keys.DisplayMngt,                            up = Keys.DisplayMngt,                      name = _('DMS Left - CMFD #1'),                                 category = {_('Stick'), _('HOTAS')},            value_down =  3.0,		value_up = 0.0},
{                                                                       down = Keys.DisplayMngt,                            up = Keys.DisplayMngt,                      name = _('DMS Right - CMFD #2'),                                category = {_('Stick'), _('HOTAS')},            value_down =  4.0,		value_up = 0.0},
{                                                                       down = Keys.DisplayMngt,                            up = Keys.DisplayMngt,                      name = _('DMS Depress - Autopilot'),                            category = {_('Stick'), _('HOTAS')},            value_down =  5.0,		value_up = 0.0},

--Throttle
{                                                                       down = Keys.GunSelDist,                             up = Keys.GunSelDist,                       name = _('Machine Gun Selection'),                              category = {_('Throttle'), _('HOTAS')},         value_down =  -1.0,		value_up = 0.0},
{                                                                       down = Keys.GunSelDist,                             up = Keys.GunSelDist,                       name = _('Machine Gun Distance'),                               category = {_('Throttle'), _('HOTAS')},         value_down =  1.0,		value_up = 0.0},
{                                                                       down = Keys.GunRearm,                               up = Keys.GunRearm,                         name = _('Machine Gun Rearm'),                                  category = {_('Throttle'), _('HOTAS')},         value_down =  -1.0,		value_up = 0.0},
{                                                                       down = Keys.Cage,                                   up = Keys.Cage,                             name = _('Cage / Uncage'),                                      category = {_('Throttle'), _('HOTAS')},         value_down =  1.0,		value_up = 0.0},
{                                                                       down = Keys.TDCX,                                   up = Keys.TDCX,                             name = _('TDC Slew Left'),                                      category = {_('Throttle'), _('HOTAS')},         value_down =  -1.0,		value_up = 0.0},
{                                                                       down = Keys.TDCX,                                   up = Keys.TDCX,                             name = _('TDC Slew Right'),                                     category = {_('Throttle'), _('HOTAS')},         value_down =  1.0,		value_up = 0.0},
{                                                                       down = Keys.TDCY,                                   up = Keys.TDCY,                             name = _('TDC Slew Up'),                                        category = {_('Throttle'), _('HOTAS')},         value_down =  1.0,		value_up = 0.0},
{                                                                       down = Keys.TDCY,                                   up = Keys.TDCY,                             name = _('TDC Slew Down'),                                      category = {_('Throttle'), _('HOTAS')},         value_down =  -1.0,		value_up = 0.0},
{                                                                       down = Keys.COM1,                                   up = Keys.COM1,                             name = _('COM Fwd - COM1 (V/UHF1)'),                            category = {_('Throttle'), _('HOTAS'), _('Communications')}, value_down =  1.0,		value_up = 0.0},
{                                                                       down = Keys.COM2,                                   up = Keys.COM2,                             name = _('COM Aft - COM2 (V/UHF2)'),                            category = {_('Throttle'), _('HOTAS'), _('Communications')}, value_down =  1.0,		value_up = 0.0},
{                                                                       down = Keys.COM3,                                   up = Keys.COM3,                             name = _('COM Up - COM3 (HF)'),                                 category = {_('Throttle'), _('HOTAS'), _('Communications')}, value_down =  1.0,		value_up = 0.0},

--NightVision               
{combos = {{key = 'H', reformers = {'RShift'}}}		   ,                down    = iCommandViewNightVisionGogglesOn   ,                                                  name = _('Toggle goggles')   ,                                  category = _('Sensors')},
{combos = {{key = 'H', reformers = {'RShift','RCtrl'}}},                pressed = iCommandPlane_Helmet_Brightess_Up  ,                                                  name = _('Gain goggles up')  ,                                  category = _('Sensors')},
{combos = {{key = 'H', reformers = {'RShift','RAlt'}}} ,                pressed = iCommandPlane_Helmet_Brightess_Down,                                                  name = _('Gain goggles down'),                                  category = _('Sensors')},


-- Autopilot
-- {combos = {{key = 'A'}},                                                down = iCommandPlaneAutopilot,                                                                  name = _('Autopilot'),                                          category = _('Autopilot')},
-- {combos = {{key = 'J'}},                                                down = iCommandPlaneAUTOnOff,                                                                   name = _('Autothrust'),                                         category = _('Autopilot')},
-- {combos = {{key = 'H'}},                                                down = iCommandPlaneSAUHBarometric,                                                             name = _('Autopilot - Barometric Altitude Hold \'H\''),         category = _('Autopilot')},
-- {combos = {{key = '1', reformers = {'LAlt'}}},                          down = iCommandPlaneStabTangBank,                                                               name = _('Autopilot - Attitude Hold'),                          category = _('Autopilot')},
-- {combos = {{key = '2', reformers = {'LAlt'}}},                          down = iCommandPlaneStabHbarBank,                                                               name = _('Autopilot - Altitude And Roll Hold'),                 category = _('Autopilot')},
-- {combos = {{key = '3', reformers = {'LAlt'}}},                          down = iCommandPlaneStabHorizon,	                                                            name = _('Autopilot - Transition To Level Flight Control'),     category = _('Autopilot')},
-- {combos = {{key = '4', reformers = {'LAlt'}}},                          down = iCommandPlaneStabHbar,                                                                   name = _('Autopilot - Barometric Altitude Hold'),               category = _('Autopilot')},
-- {combos = {{key = '5', reformers = {'LAlt'}}},                          down = iCommandPlaneStabHrad,                                                                   name = _('Autopilot - Radar Altitude Hold'),                    category = _('Autopilot')},
-- {combos = {{key = '6', reformers = {'LAlt'}}},                          down = iCommandPlaneRouteAutopilot,                                                             name = _('Autopilot - \'Route following\''),                    category = _('Autopilot')},
-- {combos = {{key = '9', reformers = {'LAlt'}}},                          down = iCommandPlaneStabCancel,                                                                 name = _('Autopilot Disengage'),                                category = _('Autopilot')},
-- {combos = {{key = 'J'}},                                                   down = iCommandPlaneAutopilotOverrideOn, up = iCommandPlaneAutopilotOverrideOff, name = _('Autopilot override'), category = _('Autopilot')},


-- Countermeasures
-- {combos = {{key = 'Q', reformers = {'LShift'}}},	                    down = iCommandPlaneDropSnar,			                                                        name = _('Countermeasures Continuously Dispense'),				category = _('Countermeasures') , features = {"Countermeasures"}},
-- {combos = {{key = 'Q'}},							                    down = iCommandPlaneDropSnarOnce,                   up = iCommandPlaneDropSnarOnceOff,          name = _('Countermeasures Release'),	                        category = _('Countermeasures') , features = {"Countermeasures"}},
{combos = {{key = 'Delete'}},						                    down = iCommandPlaneDropFlareOnce,		                                                        name = _('Countermeasures Flares Dispense'),					category = _('Countermeasures') , features = {"Countermeasures"}},
{combos = {{key = 'Insert'}},						                    down = iCommandPlaneDropChaffOnce,		                                                        name = _('Countermeasures Chaff Dispense'),						category = _('Countermeasures') , features = {"Countermeasures"}},

-- UFCP 
{									                                    down = device_commands.UFCP_0,                  up = device_commands.UFCP_0,                    name = _('UFCP 0'),			                                    category = {_('UFCP')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.UFCP},
{									                                    down = device_commands.UFCP_1,                  up = device_commands.UFCP_1,                    name = _('UFCP 1'),			                                    category = {_('UFCP')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.UFCP},
{									                                    down = device_commands.UFCP_2,                  up = device_commands.UFCP_2,                    name = _('UFCP 2'),			                                    category = {_('UFCP')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.UFCP},
{									                                    down = device_commands.UFCP_3,                  up = device_commands.UFCP_3,                    name = _('UFCP 3'),			                                    category = {_('UFCP')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.UFCP},
{									                                    down = device_commands.UFCP_4,                  up = device_commands.UFCP_4,                    name = _('UFCP 4'),			                                    category = {_('UFCP')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.UFCP},
{									                                    down = device_commands.UFCP_5,                  up = device_commands.UFCP_5,                    name = _('UFCP 5'),			                                    category = {_('UFCP')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.UFCP},
{									                                    down = device_commands.UFCP_6,                  up = device_commands.UFCP_6,                    name = _('UFCP 6'),			                                    category = {_('UFCP')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.UFCP},
{									                                    down = device_commands.UFCP_7,                  up = device_commands.UFCP_7,                    name = _('UFCP 7'),			                                    category = {_('UFCP')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.UFCP},
{									                                    down = device_commands.UFCP_8,                  up = device_commands.UFCP_8,                    name = _('UFCP 8'),			                                    category = {_('UFCP')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.UFCP},
{									                                    down = device_commands.UFCP_9,                  up = device_commands.UFCP_9,                    name = _('UFCP 9'),			                                    category = {_('UFCP')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.UFCP},
{									                                    down = device_commands.UFCP_CLR,                up = device_commands.UFCP_CLR,                  name = _('UFCP CLR'),			                                category = {_('UFCP')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.UFCP},
{									                                    down = device_commands.UFCP_ENTR,               up = device_commands.UFCP_ENTR,                 name = _('UFCP ENTR'),			                                category = {_('UFCP')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.UFCP},
{									                                    down = device_commands.UFCP_IDNT,               up = device_commands.UFCP_IDNT,                 name = _('UFCP IDNT'),			                                category = {_('UFCP')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.UFCP},
{									                                    down = device_commands.UFCP_CZ,                 up = device_commands.UFCP_CZ,                   name = _('UFCP CZ'),			                                category = {_('UFCP')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.UFCP},
{									                                    down = device_commands.UFCP_AIRSPD,             up = device_commands.UFCP_AIRSPD,               name = _('UFCP AIRSPD'),			                            category = {_('UFCP')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.UFCP},
{									                                    down = device_commands.UFCP_WARNRST,            up = device_commands.UFCP_WARNRST,              name = _('UFCP WARN RST'),			                            category = {_('UFCP')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.UFCP},
{									                                    down = device_commands.UFCP_COM1,               up = device_commands.UFCP_COM1,                 name = _('UFCP COM1'),			                                category = {_('UFCP')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.UFCP},
{									                                    down = device_commands.UFCP_COM2,               up = device_commands.UFCP_COM2,                 name = _('UFCP COM2'),			                                category = {_('UFCP')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.UFCP},
{									                                    down = device_commands.UFCP_NAVAIDS,            up = device_commands.UFCP_NAVAIDS,              name = _('UFCP NAV AIDS'),			                            category = {_('UFCP')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.UFCP},
{									                                    down = device_commands.UFCP_A_G,                up = device_commands.UFCP_A_G,                  name = _('UFCP A/G'),			                                category = {_('UFCP')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.UFCP},
{									                                    down = device_commands.UFCP_NAV,                up = device_commands.UFCP_NAV,                  name = _('UFCP NAV'),			                                category = {_('UFCP')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.UFCP},
{									                                    down = device_commands.UFCP_A_A,                up = device_commands.UFCP_A_A,                  name = _('UFCP A/A'),			                                category = {_('UFCP')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.UFCP},
{									                                    down = device_commands.UFCP_BARO_RALT,          up = device_commands.UFCP_BARO_RALT,            name = _('UFCP BARO RALT'),			                            category = {_('UFCP')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.UFCP},
{									                                    down = device_commands.UFCP_UP,                 up = device_commands.UFCP_UP,                   name = _('UFCP UP'),			                                category = {_('UFCP')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.UFCP},
{									                                    down = device_commands.UFCP_DOWN,               up = device_commands.UFCP_DOWN,                 name = _('UFCP DOWN'),			                                category = {_('UFCP')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.UFCP},
{									                                    down = device_commands.UFCP_JOY_UP,             up = device_commands.UFCP_JOY_UP,               name = _('UFCP JOY UP'),			                            category = {_('UFCP')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.UFCP},
{									                                    down = device_commands.UFCP_JOY_DOWN,           up = device_commands.UFCP_JOY_DOWN,             name = _('UFCP JOY DOWN'),			                            category = {_('UFCP')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.UFCP},
{									                                    down = device_commands.UFCP_JOY_LEFT,           up = device_commands.UFCP_JOY_LEFT,             name = _('UFCP JOY LEFT'),			                            category = {_('UFCP')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.UFCP},
{									                                    down = device_commands.UFCP_JOY_RIGHT,          up = device_commands.UFCP_JOY_RIGHT,            name = _('UFCP JOY RIGHT'),			                            category = {_('UFCP')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.UFCP},


-- CMFD1
{									                                    down = device_commands.CMFD1OSS1,               up = device_commands.CMFD1OSS1,                 name = _('CMFD1 OSS1'),			                                category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD1OSS2,               up = device_commands.CMFD1OSS2,                 name = _('CMFD1 OSS2'),			                                category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD1OSS3,               up = device_commands.CMFD1OSS3,                 name = _('CMFD1 OSS3'),			                                category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD1OSS4,               up = device_commands.CMFD1OSS4,                 name = _('CMFD1 OSS4'),			                                category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD1OSS5,               up = device_commands.CMFD1OSS5,                 name = _('CMFD1 OSS5'),			                                category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD1OSS6,               up = device_commands.CMFD1OSS6,                 name = _('CMFD1 OSS6'),			                                category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD1OSS7,               up = device_commands.CMFD1OSS7,                 name = _('CMFD1 OSS7'),			                                category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD1OSS8,               up = device_commands.CMFD1OSS8,                 name = _('CMFD1 OSS8'),			                                category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD1OSS9,               up = device_commands.CMFD1OSS9,                 name = _('CMFD1 OSS9'),			                                category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD1OSS10,              up = device_commands.CMFD1OSS10,                name = _('CMFD1 OSS10'),			                            category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD1OSS11,              up = device_commands.CMFD1OSS11,                name = _('CMFD1 OSS11'),			                            category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD1OSS12,              up = device_commands.CMFD1OSS12,                name = _('CMFD1 OSS12'),			                            category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD1OSS13,              up = device_commands.CMFD1OSS13,                name = _('CMFD1 OSS13'),			                            category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD1OSS14,              up = device_commands.CMFD1OSS14,                name = _('CMFD1 OSS14'),			                            category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD1OSS15,              up = device_commands.CMFD1OSS15,                name = _('CMFD1 OSS15'),			                            category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD1OSS16,              up = device_commands.CMFD1OSS16,                name = _('CMFD1 OSS16'),			                            category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD1OSS17,              up = device_commands.CMFD1OSS17,                name = _('CMFD1 OSS17'),			                            category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD1OSS18,              up = device_commands.CMFD1OSS18,                name = _('CMFD1 OSS18'),			                            category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD1OSS19,              up = device_commands.CMFD1OSS19,                name = _('CMFD1 OSS19'),			                            category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD1OSS20,              up = device_commands.CMFD1OSS20,                name = _('CMFD1 OSS20'),			                            category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD1OSS21,              up = device_commands.CMFD1OSS21,                name = _('CMFD1 OSS21'),			                            category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD1OSS22,              up = device_commands.CMFD1OSS22,                name = _('CMFD1 OSS22'),			                            category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD1OSS23,              up = device_commands.CMFD1OSS23,                name = _('CMFD1 OSS23'),			                            category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD1OSS24,              up = device_commands.CMFD1OSS24,                name = _('CMFD1 OSS24'),			                            category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD1OSS25,              up = device_commands.CMFD1OSS25,                name = _('CMFD1 OSS25'),			                            category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD1OSS26,              up = device_commands.CMFD1OSS26,                name = _('CMFD1 OSS26'),			                            category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD1OSS27,              up = device_commands.CMFD1OSS27,                name = _('CMFD1 OSS27'),			                            category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD1OSS28,              up = device_commands.CMFD1OSS28,                name = _('CMFD1 OSS28'),			                            category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD1ButtonBright,       up = device_commands.CMFD1ButtonBright,         name = _('CMFD1 Brightness Up'),                                category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD1ButtonBright,       up = device_commands.CMFD1ButtonBright,         name = _('CMFD1 Brightness Down'),                              category = {_('CMFD')},			            value_down =  -1.0,     value_up =  0.0,                                               cockpit_device_id = devices.CMFD},

-- CMFD2
{									                                    down = device_commands.CMFD2OSS1,               up = device_commands.CMFD2OSS1,                 name = _('CMFD2 OSS1'),			                                category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD2OSS2,               up = device_commands.CMFD2OSS2,                 name = _('CMFD2 OSS2'),			                                category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD2OSS3,               up = device_commands.CMFD2OSS3,                 name = _('CMFD2 OSS3'),			                                category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD2OSS4,               up = device_commands.CMFD2OSS4,                 name = _('CMFD2 OSS4'),			                                category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD2OSS5,               up = device_commands.CMFD2OSS5,                 name = _('CMFD2 OSS5'),			                                category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD2OSS6,               up = device_commands.CMFD2OSS6,                 name = _('CMFD2 OSS6'),			                                category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD2OSS7,               up = device_commands.CMFD2OSS7,                 name = _('CMFD2 OSS7'),			                                category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD2OSS8,               up = device_commands.CMFD2OSS8,                 name = _('CMFD2 OSS8'),			                                category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD2OSS9,               up = device_commands.CMFD2OSS9,                 name = _('CMFD2 OSS9'),			                                category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD2OSS10,              up = device_commands.CMFD2OSS10,                name = _('CMFD2 OSS10'),			                            category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD2OSS11,              up = device_commands.CMFD2OSS11,                name = _('CMFD2 OSS11'),			                            category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD2OSS12,              up = device_commands.CMFD2OSS12,                name = _('CMFD2 OSS12'),			                            category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD2OSS13,              up = device_commands.CMFD2OSS13,                name = _('CMFD2 OSS13'),			                            category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD2OSS14,              up = device_commands.CMFD2OSS14,                name = _('CMFD2 OSS14'),			                            category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD2OSS15,              up = device_commands.CMFD2OSS15,                name = _('CMFD2 OSS15'),			                            category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD2OSS16,              up = device_commands.CMFD2OSS16,                name = _('CMFD2 OSS16'),			                            category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD2OSS17,              up = device_commands.CMFD2OSS17,                name = _('CMFD2 OSS17'),			                            category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD2OSS18,              up = device_commands.CMFD2OSS18,                name = _('CMFD2 OSS18'),			                            category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD2OSS19,              up = device_commands.CMFD2OSS19,                name = _('CMFD2 OSS19'),			                            category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD2OSS20,              up = device_commands.CMFD2OSS20,                name = _('CMFD2 OSS20'),			                            category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD2OSS21,              up = device_commands.CMFD2OSS21,                name = _('CMFD2 OSS21'),			                            category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD2OSS22,              up = device_commands.CMFD2OSS22,                name = _('CMFD2 OSS22'),			                            category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD2OSS23,              up = device_commands.CMFD2OSS23,                name = _('CMFD2 OSS23'),			                            category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD2OSS24,              up = device_commands.CMFD2OSS24,                name = _('CMFD2 OSS24'),			                            category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD2OSS25,              up = device_commands.CMFD2OSS25,                name = _('CMFD2 OSS25'),			                            category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD2OSS26,              up = device_commands.CMFD2OSS26,                name = _('CMFD2 OSS26'),			                            category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD2OSS27,              up = device_commands.CMFD2OSS27,                name = _('CMFD2 OSS27'),			                            category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD2OSS28,              up = device_commands.CMFD2OSS28,                name = _('CMFD2 OSS28'),			                            category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD2ButtonBright,       up = device_commands.CMFD2ButtonBright,         name = _('CMFD2 Brightness Up'),                                category = {_('CMFD')},			            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.CMFD},
{									                                    down = device_commands.CMFD2ButtonBright,       up = device_commands.CMFD2ButtonBright,         name = _('CMFD2 Brightness Down'),                              category = {_('CMFD')},			            value_down =  -1.0,     value_up =  0.0,                                               cockpit_device_id = devices.CMFD},

{									                                    down = Keys.AviMdp1,                                                                            name = _('MDP 1 On/Off'),                                       category = {_('Electrical')}},
{									                                    down = device_commands.AviMdp1,                 up = device_commands.AviMdp1,                   name = _('MDP 1 On else Off'),                                  category = {_('Electrical')},               value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.ELECTRIC_SYSTEM},
{									                                    down = device_commands.AviMdp1,                                                                 name = _('MDP 1 On'),                                           category = {_('Electrical')},	            value_down =  1.0,                                                                     cockpit_device_id = devices.ELECTRIC_SYSTEM},
{									                                    down = device_commands.AviMdp1,                                                                 name = _('MDP 1 Off'),                                          category = {_('Electrical')},	            value_down =  0.0,                                                                     cockpit_device_id = devices.ELECTRIC_SYSTEM},

{									                                    down = Keys.AviMdp2,                                                                            name = _('MDP 2 On/Off'),                                       category = {_('Electrical')}},
{									                                    down = device_commands.AviMdp2,                 up = device_commands.AviMdp2,                   name = _('MDP 2 On else Off'),                                  category = {_('Electrical')},	            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.ELECTRIC_SYSTEM},
{									                                    down = device_commands.AviMdp2,                                                                 name = _('MDP 2 On'),                                           category = {_('Electrical')},	            value_down =  1.0,                                                                     cockpit_device_id = devices.ELECTRIC_SYSTEM},
{									                                    down = device_commands.AviMdp2,                                                                 name = _('MDP 2 Off'),                                          category = {_('Electrical')},	            value_down =  0.0,                                                                     cockpit_device_id = devices.ELECTRIC_SYSTEM},

{									                                    down = Keys.AviMst,                                                                             name = _('Avionics Master On/Off'),                             category = {_('Electrical')}},
{									                                    down = device_commands.AviMst,                  up = device_commands.AviMst,                    name = _('Avionics Master On else Off'),                        category = {_('Electrical')},	            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.ELECTRIC_SYSTEM},
{									                                    down = device_commands.AviMst,                                                                  name = _('Avionics Master On'),                                 category = {_('Electrical')},	            value_down =  1.0,                                                                     cockpit_device_id = devices.ELECTRIC_SYSTEM},
{									                                    down = device_commands.AviMst,                                                                  name = _('Avionics Master Off'),                                category = {_('Electrical')},	            value_down =  0.0,                                                                     cockpit_device_id = devices.ELECTRIC_SYSTEM},

{									                                    down = Keys.AviSms,                                                                             name = _('SMS On/Off'),                                         category = {_('Electrical')}},
{									                                    down = device_commands.AviSms,                  up = device_commands.AviSms,                    name = _('SMS On else Off'),                                    category = {_('Electrical')},	            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.ELECTRIC_SYSTEM},
{									                                    down = device_commands.AviSms,                                                                  name = _('SMS On'),                                             category = {_('Electrical')},	            value_down =  1.0,                                                                     cockpit_device_id = devices.ELECTRIC_SYSTEM},
{									                                    down = device_commands.AviSms,                                                                  name = _('SMS Off'),                                            category = {_('Electrical')},	            value_down =  0.0,                                                                     cockpit_device_id = devices.ELECTRIC_SYSTEM},

{									                                    down = Keys.AviVuhf,                                                                            name = _('V/UHF Guard/Normal'),                                 category = {_('Electrical')}},
{									                                    down = device_commands.AviVuhf,                 up = device_commands.AviVuhf,                   name = _('V/UHF Guard else Normal'),                            category = {_('Electrical')},	            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.ELECTRIC_SYSTEM},
{									                                    down = device_commands.AviVuhf,                                                                 name = _('V/UHF Guard'),                                        category = {_('Electrical')},	            value_down =  1.0,                                                                     cockpit_device_id = devices.ELECTRIC_SYSTEM},
{									                                    down = device_commands.AviVuhf,                                                                 name = _('V/UHF Normal'),                                       category = {_('Electrical')},	            value_down =  0.0,                                                                     cockpit_device_id = devices.ELECTRIC_SYSTEM},

{									                                    down = Keys.ElecBatt,                                                                           name = _('Battery On/Off'),                                     category = {_('Electrical')}},
{									                                    down = device_commands.ElecBatt,                up = device_commands.ElecBatt,                  name = _('Battery Reset else On'),                              category = {_('Electrical')},		        value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.ELECTRIC_SYSTEM},
{									                                    down = device_commands.ElecBatt,                up = device_commands.ElecBatt,                  name = _('Battery Off else On'),                                category = {_('Electrical')},		        value_down =  -1.0,     value_up =  0.0,                                               cockpit_device_id = devices.ELECTRIC_SYSTEM},
{									                                    down = device_commands.ElecBatt,                                                                name = _('Battery On'),                                         category = {_('Electrical')},		        value_down =  0.0,                                                                     cockpit_device_id = devices.ELECTRIC_SYSTEM},
{									                                    down = device_commands.ElecBatt,                                                                name = _('Battery Off'),                                        category = {_('Electrical')},		        value_down =  -1.0,                                                                    cockpit_device_id = devices.ELECTRIC_SYSTEM},
{									                                    down = device_commands.ElecBatt,                                                                name = _('Battery Reset'),                                      category = {_('Electrical')},		        value_down =  1.0,                                                                     cockpit_device_id = devices.ELECTRIC_SYSTEM},

{									                                    down = Keys.ElecGen,                                                                            name = _('Generator On/Off-Reset'),                             category = {_('Electrical')}},
{									                                    down = device_commands.ElecGen,                 up = device_commands.ElecGen,                   name = _('Generator On else Off-Reset'),                        category = {_('Electrical')},	            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.ELECTRIC_SYSTEM},
{									                                    down = device_commands.ElecGen,                                                                 name = _('Generator On'),                                       category = {_('Electrical')},	            value_down =  1.0,                                                                     cockpit_device_id = devices.ELECTRIC_SYSTEM},
{									                                    down = device_commands.ElecGen,                                                                 name = _('Generator Off-Reset'),                                category = {_('Electrical')},	            value_down =  0.0,                                                                     cockpit_device_id = devices.ELECTRIC_SYSTEM},

{									                                    down = Keys.ElecExtPwr,                                                                         name = _('External Power On/Off'),                              category = {_('Electrical')}},
{									                                    down = device_commands.ElecExtPwr,              up = device_commands.ElecExtPwr,                name = _('External Power On else Off'),                         category = {_('Electrical')},	            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.ELECTRIC_SYSTEM},
{									                                    down = device_commands.ElecExtPwr,                                                              name = _('External Power On'),                                  category = {_('Electrical')},	            value_down =  1.0,                                                                     cockpit_device_id = devices.ELECTRIC_SYSTEM},
{									                                    down = device_commands.ElecExtPwr,                                                              name = _('External Power Off'),                                 category = {_('Electrical')},	            value_down =  0.0,                                                                     cockpit_device_id = devices.ELECTRIC_SYSTEM},

{									                                    down = Keys.ElecBkp,                                                                            name = _('Backup Auto/Off'),                                    category = {_('Electrical')}},
{									                                    down = device_commands.ElecBkp,                 up = device_commands.ElecBkp,                   name = _('Backup Auto else Off'),                               category = {_('Electrical')},	            value_down =  1.0,      value_up =  0.0,                                               cockpit_device_id = devices.ELECTRIC_SYSTEM},
{									                                    down = device_commands.ElecBkp,                                                                 name = _('Generator Auto'),                                     category = {_('Electrical')},	            value_down =  1.0,                                                                     cockpit_device_id = devices.ELECTRIC_SYSTEM},
{									                                    down = device_commands.ElecBkp,                                                                 name = _('Generator Off'),                                      category = {_('Electrical')},	            value_down =  0.0,                                                                     cockpit_device_id = devices.ELECTRIC_SYSTEM},

{									                                    down = Keys.ElecEmer,                                                                           name = _('Emergency Power Emer/Auto'),                          category = {_('Electrical')}},
{									                                    down = device_commands.ElecEmer,                up = device_commands.ElecEmer,                  name = _('Emergency Power Emer else Auto'),                     category = {_('Electrical')},	            value_down =  1.0,      value_up =  -1.0,                                              cockpit_device_id = devices.ELECTRIC_SYSTEM},
{									                                    down = device_commands.ElecEmer,                                                                name = _('Emergency Power Emer'),                               category = {_('Electrical')},	            value_down =  1.0,                                                                     cockpit_device_id = devices.ELECTRIC_SYSTEM},
{									                                    down = device_commands.ElecEmer,                                                                name = _('Emergency Power Auto'),                               category = {_('Electrical')},	            value_down =  -1.0,                                                                    cockpit_device_id = devices.ELECTRIC_SYSTEM},

{									                                    down = Keys.ElecAcftIntc,                                                                       name = _('Aircraft Interconnect On/Off'),                       category = {_('Electrical')}},
{									                                    down = device_commands.ElecAcftIntc,                up = device_commands.ElecAcftIntc,          name = _('Aircraft Interconnect On else Off'),                  category = {_('Electrical')},	            value_down =  1.0,      value_up =  -1.0,                                              cockpit_device_id = devices.ELECTRIC_SYSTEM},
{									                                    down = device_commands.ElecAcftIntc,                                                            name = _('Aircraft Interconnect On'),                           category = {_('Electrical')},	            value_down =  1.0,                                                                     cockpit_device_id = devices.ELECTRIC_SYSTEM},
{									                                    down = device_commands.ElecAcftIntc,                                                            name = _('Aircraft Interconnect Off'),                          category = {_('Electrical')},	            value_down =  -1.0,                                                                    cockpit_device_id = devices.ELECTRIC_SYSTEM},

-- mirrors
{combos = {{key = 'M' }},                                               down = iCommandToggleMirrors,                                                                   name = _('Toggle Mirrors'),                                     category = {_('View Cockpit')}},


-- {combos = {{key = 'Space'}},							down = hotas_commands.STICK_TRIGGER_2ND_DETENT,		up = hotas_commands.STICK_TRIGGER_2ND_DETENT,		cockpit_device_id = devices.HOTAS,	value_down =  1.0,		value_up = 0.0,	name = _('Gun Trigger - SECOND DETENT (Press to shoot)'),				category = {_('Stick'), _('HOTAS')}},
-- {combos = {{key = ';',		reformers = {'RCtrl'}}},	pressed = hotas_commands.STICK_TRIMMER_DOWN,		up = hotas_commands.STICK_TRIMMER_DOWN,				cockpit_device_id = devices.HOTAS,	value_pressed =  1.0,	value_up = 0.0,	name = _('Trimmer Switch - PUSH(DESCEND)'),								category = {_('Stick'), _('Flight Control'), _('HOTAS')}},
-- {combos = {{key = '.',		reformers = {'RCtrl'}}},	pressed = hotas_commands.STICK_TRIMMER_UP,			up = hotas_commands.STICK_TRIMMER_UP,				cockpit_device_id = devices.HOTAS,	value_pressed =  1.0,	value_up = 0.0,	name = _('Trimmer Switch - PULL(CLIMB)'),								category = {_('Stick'), _('Flight Control'), _('HOTAS')}},
-- {combos = {{key = ',',		reformers = {'RCtrl'}}},	pressed = hotas_commands.STICK_TRIMMER_LEFT,		up = hotas_commands.STICK_TRIMMER_LEFT,				cockpit_device_id = devices.HOTAS,	value_pressed =  1.0,	value_up = 0.0,	name = _('Trimmer Switch - LEFT WING DOWN'),							category = {_('Stick'), _('Flight Control'), _('HOTAS')}},
-- {combos = {{key = '/',		reformers = {'RCtrl'}}},	pressed = hotas_commands.STICK_TRIMMER_RIGHT,		up = hotas_commands.STICK_TRIMMER_RIGHT,			cockpit_device_id = devices.HOTAS,	value_pressed =  1.0,	value_up = 0.0,	name = _('Trimmer Switch - RIGHT WING DOWN'),							category = {_('Stick'), _('Flight Control'), _('HOTAS')}},
-- {combos = {{key = 'A'}},								down = hotas_commands.STICK_PADDLE,					up = hotas_commands.STICK_PADDLE,					cockpit_device_id = devices.HOTAS,	value_down =  1.0,		value_up = 0.0,	name = _('Autopilot/Nosewheel Steering Disengage (Paddle) Switch'),		category = {_('Stick'), _('HOTAS')}},
-- {combos = {{key = 'S'}},								down = hotas_commands.STICK_UNDESIGNATE,			up = hotas_commands.STICK_UNDESIGNATE,				cockpit_device_id = devices.HOTAS,	value_down =  1.0,		value_up = 0.0,	name = _('Undesignate/Nose Wheel Steer Switch'),						category = {_('Stick'), _('HOTAS')}},
-- {combos = {{key = 'W',		reformers = {'LShift'}}},	down = hotas_commands.STICK_WEAPON_SELECT_FWD,		up = hotas_commands.STICK_WEAPON_SELECT_FWD,		cockpit_device_id = devices.HOTAS,	value_down =  1.0,		value_up = 0.0,	name = _('Select Sparrow'),												category = {_('Stick'), _('HOTAS')}},
-- {combos = {{key = 'X',		reformers = {'LShift'}}},	down = hotas_commands.STICK_WEAPON_SELECT_AFT,		up = hotas_commands.STICK_WEAPON_SELECT_AFT,		cockpit_device_id = devices.HOTAS,	value_down =  1.0,		value_up = 0.0,	name = _('Select Gun'),													category = {_('Stick'), _('HOTAS')}},
-- {combos = {{key = 'D',		reformers = {'LShift'}}},	down = hotas_commands.STICK_WEAPON_SELECT_IN,		up = hotas_commands.STICK_WEAPON_SELECT_IN,			cockpit_device_id = devices.HOTAS,	value_down =  1.0,		value_up = 0.0,	name = _('Select AMRAAM'),												category = {_('Stick'), _('HOTAS')}},
-- {combos = {{key = 'S',		reformers = {'LShift'}}},	down = hotas_commands.STICK_WEAPON_SELECT_DOWN,		up = hotas_commands.STICK_WEAPON_SELECT_DOWN,		cockpit_device_id = devices.HOTAS,	value_down =  1.0,		value_up = 0.0,	name = _('Select Sidewinder'),											category = {_('Stick'), _('HOTAS')}},
-- {combos = {{key = 'R'}},								down = hotas_commands.STICK_RECCE_EVENT_MARK,		up = hotas_commands.STICK_RECCE_EVENT_MARK,			cockpit_device_id = devices.HOTAS,	value_down =  1.0,		value_up = 0.0,	name = _('RECCE Event Mark Switch'),									category = {_('Stick'), _('HOTAS')}},	-- ATTENTION!!! not used (do not assign combos)
-- {combos = {{key = ';',		reformers = {'RAlt'}}},		down = hotas_commands.STICK_SENSOR_CONTROL_FWD,		up = hotas_commands.STICK_SENSOR_CONTROL_FWD,		cockpit_device_id = devices.HOTAS,	value_down =  1.0,		value_up = 0.0,	name = _('Sensor Control Switch - Fwd'),								category = {_('Stick'), _('HOTAS')}},
-- {combos = {{key = '.',		reformers = {'RAlt'}}},		down = hotas_commands.STICK_SENSOR_CONTROL_AFT,		up = hotas_commands.STICK_SENSOR_CONTROL_AFT,		cockpit_device_id = devices.HOTAS,	value_down =  1.0,		value_up = 0.0,	name = _('Sensor Control Switch - Aft'),								category = {_('Stick'), _('HOTAS')}},
-- {combos = {{key = ',',		reformers = {'RAlt'}}},		down = hotas_commands.STICK_SENSOR_CONTROL_LEFT,	up = hotas_commands.STICK_SENSOR_CONTROL_LEFT,		cockpit_device_id = devices.HOTAS,	value_down =  1.0,		value_up = 0.0,	name = _('Sensor Control Switch - Left'),								category = {_('Stick'), _('HOTAS')}},
-- {combos = {{key = '/',		reformers = {'RAlt'}}},		down = hotas_commands.STICK_SENSOR_CONTROL_RIGHT,	up = hotas_commands.STICK_SENSOR_CONTROL_RIGHT,		cockpit_device_id = devices.HOTAS,	value_down =  1.0,		value_up = 0.0,	name = _('Sensor Control Switch - Right'),								category = {_('Stick'), _('HOTAS')}},
-- {														down = hotas_commands.STICK_SENSOR_CONTROL_DEPRESS,	up = hotas_commands.STICK_SENSOR_CONTROL_DEPRESS,	cockpit_device_id = devices.HOTAS,	value_down =  1.0,		value_up = 0.0,	name = _('Sensor Control Switch - Depress'),							category = {_('Stick'), _('HOTAS')}},

-- {									down = cpt_commands.StickHide,		cockpit_device_id = devices.CPT_MECHANICS,	value_down =  1.0,	name = _('Control Stick - HIDE'),			category = {_('Stick'), _('HOTAS')}},
-- {									down = cpt_commands.StickHide,		cockpit_device_id = devices.CPT_MECHANICS,	value_down =  0.0,	name = _('Control Stick - SHOW'),			category = {_('Stick'), _('HOTAS')}},
-- {combos = {{key = 'Back'}},	down = cpt_commands.StickHide_EXT,	cockpit_device_id = devices.CPT_MECHANICS,	value_down =  1.0,	name = _('Control Stick - HIDE/SHOW'),		category = {_('Stick'), _('HOTAS')}},

-- {combos = {{key = 'E'}},							down = iCommandActiveJamming,			name = _('ECM'),													category = _('Countermeasures') , features = {"ECM"}},







-- -- Flight Control
-- {combos = {{key = 'T', reformers = {'LCtrl'}}}, down = iCommandPlaneTrimCancel, name = _('Trim Reset'), category = _('Flight Control')},

-- -- Sensors
-- {combos = {{key = 'Enter'}}, down = iCommandPlaneChangeLock, up = iCommandPlaneChangeLockUp, name = _('Target Lock'), category = _('Sensors')},
-- {combos = {{key = 'Back'}}, down = iCommandSensorReset, name = _('Return To Search'), category = _('Sensors')},
-- {combos = {{key = 'I'}}, down = iCommandPlaneRadarOnOff, name = _('Radar On/Off'), category = _('Sensors')},
-- {combos = {{key = 'I', reformers = {'RAlt'}}}, down = iCommandPlaneRadarChangeMode, name = _('Radar RWS/TWS Mode Select'), category = _('Sensors')},
-- {combos = {{key = 'I', reformers = {'RCtrl'}}}, down = iCommandPlaneRadarCenter, name = _('Target Designator To Center'), category = _('Sensors')},
-- {combos = {{key = 'I', reformers = {'RShift'}}}, down = iCommandPlaneChangeRadarPRF, name = _('Radar Pulse Repeat Frequency Select'), category = _('Sensors')},
-- {combos = {{key = 'O'}}, down = iCommandPlaneEOSOnOff, name = _('Electro-Optical System On/Off'), category = _('Sensors')},
-- {combos = {{key = 'O', reformers = {'RCtrl'}}}, down = iCommandPlaneNightTVOnOff, name = _('Night Vision (FLIR or LLTV) On/Off'), category = _('Sensors')},
-- {combos = {{key = ';'}}, pressed = iCommandPlaneRadarUp, up = iCommandPlaneRadarStop, name = _('Target Designator Up'), category = _('Sensors')},
-- {combos = {{key = '.'}}, pressed = iCommandPlaneRadarDown, up = iCommandPlaneRadarStop, name = _('Target Designator Down'), category = _('Sensors')},
-- {combos = {{key = ','}}, pressed = iCommandPlaneRadarLeft, up = iCommandPlaneRadarStop, name = _('Target Designator Left'), category = _('Sensors')},
-- {combos = {{key = '/'}}, pressed = iCommandPlaneRadarRight, up = iCommandPlaneRadarStop, name = _('Target Designator Right'), category = _('Sensors')},
-- {combos = {{key = ';', reformers = {'RShift'}}}, pressed = iCommandSelecterUp, up = iCommandSelecterStop, name = _('Scan Zone Up'), category = _('Sensors')},
-- {combos = {{key = '.', reformers = {'RShift'}}}, pressed = iCommandSelecterDown, up = iCommandSelecterStop, name = _('Scan Zone Down'), category = _('Sensors')},
-- {combos = {{key = ',', reformers = {'RShift'}}}, pressed = iCommandSelecterLeft, up = iCommandSelecterStop, name = _('Scan Zone Left'), category = _('Sensors')},
-- {combos = {{key = '/', reformers = {'RShift'}}}, pressed = iCommandSelecterRight, up = iCommandSelecterStop, name = _('Scan Zone Right'), category = _('Sensors')},
-- {combos = {{key = '='}}, down = iCommandPlaneZoomIn, name = _('Display Zoom In'), category = _('Sensors')},
-- {combos = {{key = '-'}}, down = iCommandPlaneZoomOut, name = _('Display Zoom Out'), category = _('Sensors')},
-- {combos = {{key = '-', reformers = {'RCtrl'}}}, down = iCommandDecreaseRadarScanArea, name = _('Radar Scan Zone Decrease'), category = _('Sensors')},
-- {combos = {{key = '=', reformers = {'RCtrl'}}}, down = iCommandIncreaseRadarScanArea, name = _('Radar Scan Zone Increase'), category = _('Sensors')},
-- {combos = {{key = '=', reformers = {'RAlt'}}}, pressed = iCommandPlaneIncreaseBase_Distance, up = iCommandPlaneStopBase_Distance, name = _('Target Specified Size Increase'), category = _('Sensors')},
-- {combos = {{key = '-', reformers = {'RAlt'}}}, pressed = iCommandPlaneDecreaseBase_Distance, up = iCommandPlaneStopBase_Distance, name = _('Target Specified Size Decrease'), category = _('Sensors')},
-- {combos = {{key = 'R', reformers = {'RShift'}}}, down = iCommandChangeRWRMode, name = _('RWR/SPO Mode Select'), category = _('Sensors')},
-- {combos = {{key = ',', reformers = {'RAlt'}}}, down = iCommandPlaneThreatWarnSoundVolumeDown, name = _('RWR/SPO Sound Signals Volume Down'), category = _('Sensors')},
-- {combos = {{key = '.', reformers = {'RAlt'}}}, down = iCommandPlaneThreatWarnSoundVolumeUp, name = _('RWR/SPO Sound Signals Volume Up'), category = _('Sensors')},

-- -- Weapons                                                                        
-- {combos = {{key = 'V', reformers = {'LCtrl'}}}, down = iCommandPlaneSalvoOnOff, name = _('Salvo Mode'), category = _('Weapons')},
-- {combos = {{key = 'Space', reformers = {'RAlt'}}}, down = iCommandPlanePickleOn,	up = iCommandPlanePickleOff, name = _('Weapon Release'), category = _('Weapons')},
-- {combos = {{key = 'C', reformers = {'LShift'}}}, down = iCommandChangeGunRateOfFire, name = _('Cut Of Burst select'), category = _('Weapons')},
-- {combos = {{key = 'H', reformers = {'RShift'}}}, down = iCommandPlaneHUDFilterOnOff, name = _('HUD Filter On Off'), category = _('Weapons')},
-- {down = iCommandPlaneRightMFD_OSB1 , name = _('MFD HUD Repeater Mode On Off'), category = _('Systems')},

})
return res
