start_custom_command   = 10000
local __count_custom = start_custom_command-1
local function __custom_counter()
	__count_custom = __count_custom + 1
	return __count_custom
end


Keys =
{

    --AutoStartDeviceRelated          = 414,
	iCommandPlaneIncreaseBase_Distance= 412,

    iCommandPlaneJettisonFuelTanks  = 178,
    iCommandPlaneJettisonFuelTanksUp= 170,

    iCommandPlaneFire               = 84,     -- PickleOn + iCommandPlaneFire = FireBurst without burst limit
    iCommandPlaneFireOff            = 85,     -- PickleOn + iCommandPlaneFireOff = Stop Burst



    iCommandSwitchMasterArm	        = 283,      --Toggles MasterArm


    PlanePickleOn	                = 350,
	PlanePickleOff	                = 351,
    
    
    PlaneChgWeapon                  = 101,
    PlaneChgTargetNext              = 102,    -- iCommandPlaneChangeTarget
    PlaneModeNAV                    = 105,
    PlaneModeBVR                    = 106,
    PlaneModeVS                     = 107,
    PlaneModeBore                   = 108,
    PlaneModeGround                 = 111,

	Canopy                          = 71,
	
	PlaneAirBrake                   = 73,
	PlaneAirBrakeOn                 = 147,
	PlaneAirBrakeOff                = 148,	
	
	PlaneFlaps                      = 72,
	PlaneFlapsOn                    = 145, -- Fully down
	PlaneFlapsOff                   = 146, -- Fully up
    	
	PlaneGear                       = 68,						-- Шасси
	PlaneGearUp	                    = 430,
	PlaneGearDown                   = 431,
    
   
	LeftEngineStart = 311,			-- ?????? ?????? ?????????
	RightEngineStart = 312,			-- ?????? ??????? ?????????

	LeftEngineStop = 313,				-- ?????????? ?????? ?????????
    RightEngineStop = 314,			-- ?????????? ??????? ?????????
    


	PowerOnOff                      = 315,

    AltimeterPressureIncrease = 316,  
    AltimeterPressureDecrease = 317,
    AltimeterPressureStop = 318,       

    PlaneLightsOnOff                = 175,
    PlaneHeadlightOnOff             = 328,

    PowerGeneratorLeft              = 711,
    PowerGeneratorRight             = 712,

    BatteryPower                    = 1073,   -- iCommandBatteryPower

    PlaneChgTargetPrev              = 1315,   -- iCommandPlaneUFC_STEER_DOWN

    -- add custom commands here --

    ---- A-29B
    EngineStart                     = __custom_counter(),
    EngineStartCenter               = __custom_counter(),
    EngineStartInterrupt            = __custom_counter(),

    Engine_Stop                     = __custom_counter(),

	PlaneFireOn		                = __custom_counter(), -- replaces iCommandPlaneFire
	PlaneFireOff	                = __custom_counter(), -- replaces iCommandPlaneFireOff
    PickleOn                        = __custom_counter(), -- replaces iCommandPlanePickleOn
    PickleOff                       = __custom_counter(), -- replaces iCommandPlanePickleOff


    -- Stick
    StickStep		    	 = __custom_counter(),
    StickDesignate        	     = __custom_counter(),
    StickUndesignate      	     = __custom_counter(),
    MasterModeSw      	     = __custom_counter(),
    APDisengage      	     = __custom_counter(),
    APOvrd      	     = __custom_counter(),
    Call      	     = __custom_counter(),
    Trigger      	     = __custom_counter(),
    WeaponRelease			    	 = __custom_counter(),
    DisplayMngt        	     = __custom_counter(),
    JettisonWeapons         =   __custom_counter(),

    -- Throttle
    GunSelDist        	     = __custom_counter(),
    GunRearm        	     = __custom_counter(),
    Cage        	     = __custom_counter(),
    TDCX        	     = __custom_counter(),
    TDCY        	     = __custom_counter(),
    AirBrake           = __custom_counter(),
    Cutoff            = __custom_counter(),

    AviMdp1                     = __custom_counter(),
    AviMdp2                     = __custom_counter(),
    AviMst                     = __custom_counter(),
    AviSms                     = __custom_counter(),
    AviVuhf                     = __custom_counter(),

    ElecBatt                     = __custom_counter(),
    ElecGen                     = __custom_counter(),
    ElecAcftIntc                 = __custom_counter(),
    ElecExtPwr                     = __custom_counter(),
    ElecBkp                     = __custom_counter(),
    ElecEmer                     = __custom_counter(),

    COM1                     = __custom_counter(),
    COM2                     = __custom_counter(),
    COM3                     = __custom_counter(),

}

start_command   = 3000
local __count = start_command-1
local function __counter()
	__count = __count + 1
	return __count
end

device_commands =
{
    Button_Test                     = __counter(),
    arm_gun                         = __counter(),
    arm_master                      = __counter(),
    arm_station1                    = __counter(),
    arm_station2                    = __counter(),
    arm_station3                    = __counter(),
    arm_station4                    = __counter(),
    arm_station5                    = __counter(),
    arm_func_selector               = __counter(),
    gunpod_l                        = __counter(),
    gunpod_c                        = __counter(),
    gunpod_r                        = __counter(),
    gunpod_chargeclear              = __counter(),
	push_starter_switch             = __counter(),
    flaps                           = __counter(),
	spoiler_cover                   = __counter(),
	spoiler_arm                     = __counter(),
    FuelGaugeExtButton              = __counter(),
    AltPressureKnob                 = __counter(),
    AltPressureStd                  = __counter(),
    Gear                            = __counter(),
    Hook                            = __counter(),
    emer_gen_bypass                 = __counter(),
    emer_gen_deploy                 = __counter(),
    speedbrake                      = __counter(),
    arm_emer_sel                    = __counter(),
    arm_bomb                        = __counter(),
    emer_bomb_release               = __counter(),
    GunsightKnob                    = __counter(),
    GunsightDayNight                = __counter(),
    GunsightBrightness              = __counter(),
    AWRS_quantity                   = __counter(),
    AWRS_drop_interval              = __counter(),
    AWRS_multiplier                 = __counter(),
    AWRS_stepripple                 = __counter(),
    speedbrake_emer                 = __counter(),
    emer_gear_release               = __counter(),
    radar_alt_indexer               = __counter(),
    radar_alt_switch                = __counter(),
    master_test                     = __counter(),
    ias_index_button                = __counter(),
    ias_index_knob                  = __counter(),
    stby_att_index_button           = __counter(),
    stby_att_index_knob             = __counter(),

    bdhi_mode                       = __counter(),

    doppler_select                  = __counter(),
    doppler_memory_test             = __counter(),

    nav_select                      = __counter(),
    asn41_magvar                    = __counter(),
    asn41_windspeed                 = __counter(),
    asn41_winddir                   = __counter(),
    ppos_lat                        = __counter(),
    ppos_lon                        = __counter(),
    dest_lat                        = __counter(),
    dest_lon                        = __counter(),

    radar_planprofile               = __counter(),
    radar_range                     = __counter(),
    radar_storage                   = __counter(),
    radar_brilliance                = __counter(),
    radar_detail                    = __counter(),
    radar_gain                      = __counter(),
    radar_filter                    = __counter(),
    radar_reticle                   = __counter(),
    radar_mode                      = __counter(),
    radar_aoacomp                   = __counter(),
    radar_angle                     = __counter(),
    radar_angle_axis                = __counter(),
    radar_angle_axis_abs            = __counter(),
    radar_volume                    = __counter(),
    tacan_mode                      = __counter(),
    tacan_ch_major                  = __counter(),
    tacan_ch_minor                  = __counter(),
    tacan_volume                    = __counter(),
    extlight_master                 = __counter(),
    extlight_probe                  = __counter(),
    extlight_taxi                   = __counter(),
    extlight_anticoll               = __counter(),
    extlight_fuselage               = __counter(),
    extlight_flashsteady            = __counter(),
    extlight_nav                    = __counter(),
    extlight_tail                   = __counter(),
    intlight_whiteflood             = __counter(),
    intlight_instruments            = __counter(),
    intlight_console                = __counter(),
    intlight_brightness             = __counter(),
    rudder_trim                     = __counter(),
    throttle_axis                   = __counter(),
    throttle_click                  = __counter(),

    afcs_standby                    = __counter(),
    afcs_engage                     = __counter(),
    afcs_hdg_sel                    = __counter(),
    afcs_alt                        = __counter(),
    afcs_hdg_set                    = __counter(),
    afcs_stab_aug                   = __counter(),
    afcs_ail_trim                   = __counter(),

    apc_engagestbyoff               = __counter(),
    apc_hotstdcold                  = __counter(),

    arc51_mode                      = __counter(),
    arc51_xmitmode                  = __counter(),
    arc51_volume                    = __counter(),
    arc51_squelch                   = __counter(),
    arc51_freq_preset               = __counter(),
    arc51_freq_XXxxx                = __counter(),
    arc51_freq_xxXxx                = __counter(),
    arc51_freq_xxxXX                = __counter(),

    clock_stopwatch                 = __counter(),

    cm_bank                         = __counter(),
    cm_auto                         = __counter(),
    cm_adj1                         = __counter(),
    cm_adj2                         = __counter(),
    cm_pwr                          = __counter(),

    accel_reset                     = __counter(),
	
	throttle_axis_mod               = __counter(),
	
	ecm_apr25_off	                = __counter(),
	ecm_apr25_audio	                = __counter(),
	ecm_apr27_off	                = __counter(),
	
	ecm_systest_upper	            = __counter(),
	ecm_systest_lower	            = __counter(),
	
	ecm_msl_alert_axis_inner	    = __counter(),
	ecm_msl_alert_axis_outer	    = __counter(),
	
	ecm_selector_knob               = __counter(),
	
	pitch_axis_mod 	                = __counter(),
	roll_axis_mod 	                = __counter(),
	rudder_axis_mod                 = __counter(),
	wheelbrake_AXIS 	            = __counter(),

    shrike_sidewinder_volume        = __counter(),

    AWRS_drop_interval_AXIS         = __counter(),
    intlight_whiteflood_AXIS        = __counter(),
    intlight_instruments_AXIS       = __counter(),
    intlight_console_AXIS           = __counter(),
    intlight_whiteflood_CHANGE      = __counter(),
    intlight_instruments_CHANGE     = __counter(),
    intlight_console_CHANGE         = __counter(),
    
    cabin_pressure                  = __counter(),
    windshield_defrost              = __counter(),
    cabin_temp                      = __counter(),

    man_flt_control_override        = __counter(),
    
    shrike_selector                 = __counter(),
    oxygen_switch                   = __counter(),
    
    COMPASS_set_heading             = __counter(),
    COMPASS_push_to_sync            = __counter(),
    COMPASS_free_slaved_switch      = __counter(),
    COMPASS_latitude                = __counter(),
    
    ENGINE_wing_fuel_sw             = __counter(),
    ENGINE_drop_tanks_sw            = __counter(),
    ENGINE_fuel_control_sw          = __counter(),
    ENGINE_manual_fuel_shutoff        = __counter(),
    ENGINE_manual_fuel_shutoff_catch  = __counter(),

    CPT_shoulder_harness            = __counter(),
    CPT_secondary_ejection_handle   = __counter(),
    ppos_lat_push                   = __counter(),
    ppos_lon_push                   = __counter(),
    dest_lat_push                   = __counter(),
    dest_lon_push                   = __counter(),
    asn41_magvar_push               = __counter(),
    asn41_windspeed_push            = __counter(),
    asn41_winddir_push              = __counter(),

    throttle_click_ITER             = __counter(),

    JATO_arm                        = __counter(),
    JATO_jettison                   = __counter(),

    GunsightElevationControl_AXIS   = __counter(),
    pilot_salute                    = __counter(),

    left_wheelbrake_AXIS            = __counter(),
    right_wheelbrake_AXIS           = __counter(),

    AOA_dimming_wheel_AXIS          = __counter(),

    EngineStart                     = __counter(),
    EnginePMU                       = __counter(),
    EngineIgnition                  = __counter(),
    EngineInnSep                    = __counter(),

    ExtLightSearch                  = __counter(),
    ExtLightBeacon                  = __counter(),
    ExtLightStrobe                  = __counter(),
    ExtLightInfrared                = __counter(),
    ExtLightNormal                  = __counter(),
    ExtLightNav                     = __counter(),
    ExtLightTaxi                    = __counter(),
    ExtLightLng                     = __counter(),

    ElecBatt                        = __counter(),
    ElecGen                         = __counter(),
    ElecAC                          = __counter(),
    ElecExtPwr                      = __counter(),
    ElecBkp                         = __counter(),
    ElecEmer                        = __counter(),
    ElecAcftIntc                    = __counter(),

    IcePropeller                    = __counter(),
    IceWindshield                   = __counter(),
    IcePitotPri                     = __counter(),
    IcePitotSec                     = __counter(),

    IntLightPnl                     = __counter(),
    IntLightStorm                   = __counter(),
    IntLightCsl                     = __counter(),
    IntLightAlm                     = __counter(),
    IntLightChart                   = __counter(),
    IntLightNvg                     = __counter(),

    AviMdp1                     = __counter(),
    AviMdp2                     = __counter(),
    AviMst                     = __counter(),
    AviSms                     = __counter(),
    AviVuhf                     = __counter(),

    EnvTemp                     = __counter(),
    EnvAC                     = __counter(),
    EnvECS                     = __counter(),
    EnvRecFan                     = __counter(),

    Salvo                     = __counter(),
    LndGear                     = __counter(),
    LndGearBeep                     = __counter(),
    LndGearOvr                     = __counter(),
    LndGearEmer                     = __counter(),
    FuelMain                     = __counter(),
    FuelAux                     = __counter(),
    FuelXfr                     = __counter(),
    SeatAdj                     = __counter(),
    EmerSpdBrk                  = __counter(),
    FuelHydBleed                = __counter(),
    AntiG                       = __counter(),
    TrimEmerAil                 = __counter(),
    TrimEmerElev                = __counter(),
    AutoRudder                  = __counter(),
    Flaps                       = __counter(),
    Friction                    = __counter(),

    EmerParkBrake               = __counter(),

    EltOn                       = __counter(),
    PicNavMan                   = __counter(),
    PicNavSlave               = __counter(),

    Mass               = __counter(),
    LateArm                    = __counter(),
    

    AudioNormal               = __counter(),

    BFI_BRIGHT      = __counter(),
    
    ASICage                     = __counter(),
    ASIAdjust                   = __counter(),

    CMFD1OSS1                 = __counter(),
    CMFD1OSS2                 = __counter(),
    CMFD1OSS3                 = __counter(),
    CMFD1OSS4                = __counter(),
    CMFD1OSS5                 = __counter(),
    CMFD1OSS6                 = __counter(),
    CMFD1OSS7                 = __counter(),
    CMFD1OSS8                 = __counter(),
    CMFD1OSS9                 = __counter(),
    CMFD1OSS10                 = __counter(),
    CMFD1OSS11                 = __counter(),
    CMFD1OSS12                 = __counter(),
    CMFD1OSS13                 = __counter(),
    CMFD1OSS14                = __counter(),
    CMFD1OSS15                 = __counter(),
    CMFD1OSS16                 = __counter(),
    CMFD1OSS17                 = __counter(),
    CMFD1OSS18                 = __counter(),
    CMFD1OSS19                 = __counter(),
    CMFD1OSS20                 = __counter(),
    CMFD1OSS21                 = __counter(),
    CMFD1OSS22                 = __counter(),
    CMFD1OSS23                 = __counter(),
    CMFD1OSS24                = __counter(),
    CMFD1OSS25                 = __counter(),
    CMFD1OSS26                 = __counter(),
    CMFD1OSS27                 = __counter(),
    CMFD1OSS28                 = __counter(),
    CMFD1ButtonOn                 = __counter(),
    CMFD1ButtonGain                 = __counter(),
    CMFD1ButtonSymb                 = __counter(),
    CMFD1ButtonBright                 = __counter(),

    CMFD2OSS1                 = __counter(),
    CMFD2OSS2                 = __counter(),
    CMFD2OSS3                 = __counter(),
    CMFD2OSS4                = __counter(),
    CMFD2OSS5                 = __counter(),
    CMFD2OSS6                 = __counter(),
    CMFD2OSS7                 = __counter(),
    CMFD2OSS8                 = __counter(),
    CMFD2OSS9                 = __counter(),
    CMFD2OSS10                 = __counter(),
    CMFD2OSS11                 = __counter(),
    CMFD2OSS12                 = __counter(),
    CMFD2OSS13                 = __counter(),
    CMFD2OSS14                = __counter(),
    CMFD2OSS15                 = __counter(),
    CMFD2OSS16                 = __counter(),
    CMFD2OSS17                 = __counter(),
    CMFD2OSS18                 = __counter(),
    CMFD2OSS19                 = __counter(),
    CMFD2OSS20                 = __counter(),
    CMFD2OSS21                 = __counter(),
    CMFD2OSS22                 = __counter(),
    CMFD2OSS23                 = __counter(),
    CMFD2OSS24                = __counter(),
    CMFD2OSS25                 = __counter(),
    CMFD2OSS26                 = __counter(),
    CMFD2OSS27                 = __counter(),
    CMFD2OSS28                 = __counter(),
    CMFD2ButtonOn                 = __counter(),
    CMFD2ButtonGain                 = __counter(),
    CMFD2ButtonSymb                 = __counter(),
    CMFD2ButtonBright                 = __counter(),

    ClockSel                      = __counter(),
    ClockCtrl                      = __counter(),

    UFCP_COM1                      = __counter(),
    UFCP_COM2                      = __counter(),
    UFCP_COM3                      = __counter(),
    UFCP_NAVAIDS                      = __counter(),
    UFCP_A_G                      = __counter(),
    UFCP_NAV                      = __counter(),
    UFCP_A_A                      = __counter(),
    UFCP_BARO_RALT                      = __counter(),
    UFCP_IDNT                      = __counter(),
    UFCP_1                      = __counter(),
    UFCP_2                      = __counter(),
    UFCP_3                      = __counter(),
    UFCP_4                      = __counter(),
    UFCP_5                      = __counter(),
    UFCP_6                      = __counter(),
    UFCP_7                      = __counter(),
    UFCP_8                      = __counter(),
    UFCP_9                      = __counter(),
    UFCP_0                      = __counter(),
    UFCP_UP                      = __counter(),
    UFCP_DOWN                      = __counter(),
    UFCP_CLR                      = __counter(),
    UFCP_ENTR                      = __counter(),
    UFCP_CZ                      = __counter(),
    UFCP_AIRSPD                      = __counter(),
    UFCP_WARNRST                      = __counter(),
    UFCP_DAY_NIGHT                      = __counter(),
    UFCP_RALT                      = __counter(),
    UFCP_DVR                      = __counter(),
    UFCP_EGI                      = __counter(),
    UFCP_UFC                      = __counter(),
    UFCP_HUD_TEST                      = __counter(),
    UFCP_SBS_ON                      = __counter(),
    UFCP_HUD_BRIGHT                      = __counter(),
    UFCP_SBS_ADJUST                      = __counter(),
    UFCP_JOY_RIGHT                      = __counter(),
    UFCP_JOY_LEFT                      = __counter(),
    UFCP_JOY_UP                      = __counter(),
    UFCP_JOY_DOWN                      = __counter(),
    UFCP_VV                      = __counter(),

    ALERTS_SET_WARNING                      = __counter(),
    ALERTS_RESET_WARNING                      = __counter(),
    ALERTS_ACK_WARNING                      = __counter(),
    ALERTS_ACK_WARNINGS                      = __counter(),
    
    ALERTS_SET_CAUTION                      = __counter(),
    ALERTS_RESET_CAUTION                      = __counter(),
    ALERTS_ACK_CAUTION                      = __counter(),
    ALERTS_ACK_CAUTIONS                      = __counter(),

    ALERTS_SET_ADVICE                      = __counter(),
    ALERTS_RESET_ADVICE                      = __counter(),
    
    WARNING_PRESS                      = __counter(),
    CAUTION_PRESS                      = __counter(),

    WPN_SELECT_STO                          = __counter(),
    WPN_AA_STEP                          = __counter(),
    WPN_AA_SIGHT_STEP                    = __counter(),
    WPN_AA_RR_SRC_STEP                    = __counter(),
    WPN_AA_SLV_SRC_STEP                    = __counter(),
    WPN_AA_COOL_STEP                    = __counter(),
    WPN_AA_SCAN_STEP                    = __counter(),
    WPN_AA_LIMIT_STEP                    = __counter(),

    WPN_AG_STEP                          = __counter(),

    STICK_WEAPON_RELEASE                    = __counter(),
    STICK_TRIGGER_2ND_DETENT                    = __counter(),
    STICK_PADDLE                    = __counter(),
    NAV_INC_FYT                    = __counter(),
    NAV_DEC_FYT                    = __counter(),
    NAV_SET_FYT                    = __counter(),
    
    
    AUDIO_COM1_VOL                    = __counter(),
    AUDIO_COM2_VOL                    = __counter(),
    AUDIO_COM3_VOL                    = __counter(),
    AUDIO_COM4_VOL                    = __counter(),
    AUDIO_ADF_VOL                    = __counter(),
    AUDIO_NAV_VOL                    = __counter(),
    AUDIO_MSL_VOL                    = __counter(),
    AUDIO_MKR_VOL                    = __counter(),
    AUDIO_VOL                    = __counter(),
    AUDIO_VOX                    = __counter(),
    AUDIO_INPH                    = __counter(),

    AP_RP                    = __counter(),
    AP_HDG                    = __counter(),
    AP_ALT                    = __counter(),
    AP_TEST                    = __counter(),
    AP_NAV                    = __counter(),
    AP_APR                    = __counter(),
    AP_GS                    = __counter(),
    AP_ON                    = __counter(),



    AAA                    = __counter(),

    STICK_WEAPON_RELEASE_OFF                = __counter(),
    WPN_AG_LAUNCH_OP_STEP                    = __counter(),
	
    ThrottleAxis                        = __counter(),
    ThrottleClick                        = __counter(),

}



-- if command == 0x55 then
--     stop_fire();
-- elseif command == 0x54 and pickle_on then
--     start_fire();
-- elseif command == 0x65 then
    


-- end



-- *** fenv:
-- iCommandPlaneThreatWarnSoundVolumeDown	409
-- iCommandGLaserRangerReset	1632
-- iCommandPlaneRightMFD_OSB18	689
-- iCommandViewTempCockpitOff	18
-- iCommandPlane_Env_WindshieldDefogDeice	1509
-- iCommandViewNeutrals	25
-- iCommandDebugAxis9	2096
-- iCommandHelicopter_TC_RPM	820
-- iCommand_IlluminationInterf_ADI_AHR_Illumination_brightness_up	940
-- iCommandPlane_R_800_ADF_Sound_switch	618
-- iCommandViewPitCameraMoveStop	490
-- iCommandPlaneLeftMFD_CON_Increase	668
-- iCommandPlane_HOTAS_MIC_SwitchDown	573
-- iCommandPlaneRightMFD_ADJ_Decrease	693
-- iCommandPlane_GroundMovingTarget	527
-- iCommandPlaneFSLeftMainBoostPump	1087
-- iCommandPlane_Helmet_Brightess_Up	840
-- iCommandLaserRangeModeSwitchCover	886
-- iCommandHelicopter_SignalFlares_RED	830
-- iCommandPlaneUHFTestDisplay	1213
-- iCommandPlaneCMSC_JMR	1347
-- iCommandPlaneLeftMFD_OSB13	654
-- iCommandPlaneNav_PB2_off	860
-- iCommandPlaneViewHorizontal	2007
-- iCommandNaturalViewCockpitOut	130
-- iCommandPlaneCMSP_BRT_DEC	1332
-- iCommandPlane_HOTAS_TriggerSecondStage	554
-- iCommandPlaneAUTUnlockRight	173
-- iCommandPlaneNav_CourseTimeRange_off	879
-- iCommandPlaneRightMFD_OSB4_Off	1010
-- iCommand_FireExting_Signals	927
-- iCommand_ENG_INTERF_Right_Engine_RT_12_6	904
-- iCommandPlaneAUTUnlockLeft	172
-- iCommandPlaneCMSP_OSB_4	1327
-- iCommandPlaneUFC_5	1299
-- iCommandDownPilon	4
-- iCommandElectronicControlSystemRightEngine	743
-- iCommandViewCameraDownSlow	48
-- iCommandPlaneIntercomFMIncrease	1165
-- iCommandPlaneRightMFD_OSB17_Off	1023
-- iCommandPlane_SPU9_SPU_9_on_off	629
-- iCommandViewLongitudeTransAbs	2053
-- iCommandPlaneWheelBrakeRightOff	964
-- iCommandPlaneAUTIncreaseRegime	66
-- iCommandPlaneCMSP_MODE_OFF	1342
-- iCommandAutoLockOnNearestAircraft	272
-- iCommandViewAngleDefault	177
-- iCommandPlaneCDU_L	1265
-- iCommandPlane_ILS_MHz_Decrease	1439
-- iCommandPlaneSelecterHorizontal	2031
-- iCommandPlane_R_828_Channel_prevous	623
-- iCommandViewMe	21
-- iCommandPlaneConsoleLightsIncrease	1373
-- iCommandPlaneSAUHorizon	61
-- iCommandLeftEngineFuelValveShutOffCover	723
-- iCommand_LWS_Reset	885
-- iCommandViewDownSlow	35
-- iCommandPlaneCDU_P	1269
-- iCommandPlaneCDU_6	1247
-- iCommandPlane_VHF_FM_01MHz_Dec	1477
-- iCommandPlaneRightMFD_OSB10	681
-- iCommandPlaneRightMFD_BRT_Increase	696
-- iCommandPlaneNav_BearingRangeT_off	882
-- iCommandPlane_Oxygen_TestMark	1505
-- iCommandPlaneQuickPadlockOff	1068
-- iCommandPlaneAUTIncrease	64
-- iCommandPlaneEmerElevatorDisengageL	1110
-- iCommand_LWS_BIT_On	893
-- iCommandIFFAntennaLower	1552
-- iCommandPlaneCircuitBreaker_28	1142
-- iCommandPowerBattery1	706
-- iCommandPlaneIntercomINTDecrease	1161
-- iCommandPlane_R_800_Test	620
-- iCommandPlaneAHCPIFFCCOff	1393
-- iCommandPlaneRightMFD_OSB13	684
-- iCommandPowerBattery2	708
-- iCommandControlPanelIllumination	814
-- iCommand_UV26_PowerCover	896
-- iCommandAutoLockOnNextAircraft	274
-- iCommandPlaneDLK_Target3_up	782
-- iCommandChangeRippleQuantity	281
-- iCommandViewVertTrans	2050
-- iCommandPlaneCircuitBreaker_16	1130
-- iCommand_SHKVAL_scan_vel_down	917
-- f	userdata: 00000000272418E8
-- iCommandPlaneCDU_LSK_7R	1234
-- iCommandPlaneCMSP_OSB_1	1324
-- iCommandNaturalViewCockpitIn	129
-- iCommandPlaneCircuitBreaker_22	1136
-- iCommandPlane_ABRIS_Power	495
-- iCommandPlaneZoomIn	103
-- iCommandViewTempCockpitToggle	237
-- iCommandPlaneAirRefuel	155
-- iCommandPlane_FireRate	535
-- iCommandPlaneNav_PB3_off	861
-- iCommandCockpitClickModeOnOff	363
-- iCommandPlane_I251_Contrast_Up	844
-- iCommandPlaneCDU_LSK_5L	1229
-- iCommandPlane_HOTAS_PinkySwitchAft	569
-- iCommandPlaneIntercomINTIncrease	1162
-- iCommandGroundPowerAC	710
-- iCommandCockpitCursorVerticalAbs	2039
-- iCommandViewLocomotivesToggle	348
-- iCommandHelicopter_PPR_button_DIR_up	305
-- iCommandPlaneCMSP_MWS_MENU	1334
-- iCommandPlane_ADF_Channel_prevous	582
-- iCommandPlane_HOTAS_NoseWheelSteeringButton	562
-- iCommand_CPT_MECH_WindscreenWiper_Speed	883
-- iCommandAutoLockOnNextSurfaceTarget	278
-- iCommandViewSnapView6	402
-- iCommandPlaneUHFVolumeDec	1216
-- iCommand_LWS_Power	895
-- iCommandPlaneVOID_1	1280
-- iCommandPlaneModeNAV	105
-- iCommandPlaneCMSC_BRT_INC	1350
-- iCommandSoundOnOff	122
-- iCommand_ENG_INTERF_Left_Engine_RT_12_6	905
-- iCommandPlaneCDU_PLUS	1293
-- iCommandPlaneYawSASEngageR	1154
-- iCommandPlane_ABRIS_BT_4_up	808
-- iCommandViewAWACSLastZoomY1	2060
-- iCommandPlaneCDU_DIM	1287
-- iCommandPlane_VHF_AM_Volume_Inc	1482
-- iCommandElectricalPowerInverter	713
-- iCommandPlaneUHFFreqModeDialGRD	1224
-- iCommandPlaneModeGround	111
-- iCommandPlaneFSLeftWingBoostPump	1083
-- iCommandPlaneIntercomFMPress	1166
-- iCommandViewDownRight	206
-- ICommandMenuItem2	967
-- iCommandPlane_SpotLight_left	511
-- iCommandPlaneDoAndHome	114
-- iCommandPlane_Peak_Vol_Increase	1458
-- iCommandPlaneUFC_SEL_DOWN	1319
-- iCommandViewUnlock	20
-- iCommandWeaponsControlSystem	734
-- iCommandViewCameraBaseReturn	352
-- iCommandPlaneCMDDispenceStopOff	367
-- iCommandDebugAxis7	2094
-- iCommandViewCameraRight	42
-- iCommandPlane_Env_TempPress_DUMP	1517
-- iCommandHelicopter_APU_stop_up	804
-- iCommandPlaneNav_PB8_off	866
-- iCommandChangeGunRateOfFire	280
-- iCommandHelicopter_Selected_Engine_start	596
-- iCommandPlaneAUTIncreaseRegimeRight	167
-- iCommandViewHorStop	295
-- iCommandPlane_ABRIS_Axis_Increase_up	810
-- iCommandGLaserRangerOff	1631
-- iCommandPlaneCMDChangeRippleInterval	370
-- iCommandPlane_ReadjustFreeTurbineRPM_Up	853
-- iCommandPlaneHarsSasNormOverride	1197
-- iCommandPlane_R_800_Modulation_change	616
-- iCommandPlane_I251_Contrast_Down	845
-- iCommandGEmissionToggle	1624
-- iCommandPlaneRadarHorizontalAbs	2027
-- iCommand_FireExting_TestGroups	931
-- iCommandPlane_HOTAS_TargetManagementSwitchUp	544
-- iCommandViewCockpitSetGunnerSeat2	1606
-- iCommandPlane_HOTAS_MasterModeControlButton	561
-- iCommandHelicopter_SelectWeapon_External	825
-- iCommandPlaneFuelOff	80
-- iCommandPlane_HARS_Mode	1445
-- iCommandHelicopter_SignalFlares_YELLOW	832
-- iCommandPlaneTrimRudder	2021
-- iCommandPlaneCMSP_MODE_STBY	1343
-- iCommandPlaneNav_PB6_off	864
-- iCommandPlaneFloodLightsIncrease	1371
-- iCommandRecoverHuman	327
-- iCommandPlane_HOTAS_CoolieDown	540
-- iCommandPlaneDLK_Erase_up	789
-- iCommandPlaneCircuitBreaker_2	1116
-- iCommandPlaneCMSC_SEP	1354
-- iCommandFlightClockReset	288
-- iCommandDatalinkUHF_TLK	715
-- iCommandPlaneLeftMFD_OSB1	642
-- iCommandHelicopter_APU_stop	598
-- iCommandGLockon	1580
-- iCommandPlaneNav_Cancel_off	876
-- iCommandPlane_SpotSelect_switch	517
-- iCommandLeftWheelBrake	2112
-- iCommandPlaneAHCPTGPOnOff	1383
-- iCommandPlane_VHF_FM_10MHz_Inc	1474
-- iCommandHelicopter_SignalFlares_GREEN	829
-- iCommandPlaneLeftMFD_SYM_Up	670
-- iCommandPlaneCancelWeaponsDelivery_up	799
-- iCommandPlane_ADF_Volume_down	587
-- iCommand_FireExting_ReservoirsCover	929
-- iCommandViewHUDOnlyOnOff	326
-- iCommandPlaneFSReceiverLever	1091
-- iCommandPlaneConsoleLightsDecrease	1372
-- iCommandEnginesStop	310
-- iCommandPlane_HOTAS_TargetManagementSwitchRight	547
-- iCommandTransferCursor	306
-- iCommandPlaneRightMFD_OSB8_Off	1014
-- iCommandPlaneStabHbar	389
-- iCommandPlaneNav_POS_corrMode_off	870
-- iCommandPlaneFlapsOff	146
-- iCommand_VMS_ALMAZ_UP_Check	902
-- iCommandLoadGame	256
-- iCommandPlaneThrottleFrictionInc	1070
-- iCommandViewAWACSTargetUnits	2085
-- iCommandAPUFuelValveShutOffCover	727
-- iCommandRightEngineFuelValveShutOff	724
-- iCommandPlane_HOTAS_MIC_SwitchUp	572
-- iCommandViewFight	14
-- iCommandViewBtn1Up	1596
-- iCommandViewExternalZoomOutStop	337
-- iCommand_ENG_INTERF_EngVibrDetectorBIT	906
-- iCommandPlaneFSRefuelLigtingIncrease	1099
-- iCommandPlaneDLK_Wingman2_up	785
-- iCommandPlaneRightMFD_OSB7	678
-- iCommandPlaneRightMFD_CON_Increase	698
-- iCommandThrottleIncrease	1032
-- iCommandPlaneSignalLTS	1366
-- iCommandPlane_HOTAS_CMS_Up	556
-- iCommandViewStop	209
-- iCommandViewEnemies	24
-- iCommandPlane_R_800_2nd_wheel_up	609
-- iCommandPlanePitchSASEngageL	1155
-- iCommandPlane_VHF_AM_10MHz_Dec	1495
-- iCommandPowerGeneratorRight	712
-- iCommandTrackEditInsert	320
-- iCommandViewAWACSUnitInfoOn	423
-- iCommandTrainingUserRespondedBack	1628
-- iCommandPlaneDesignate_CageOn_vertical	441
-- iCommandPlaneDLK_Target1_up	780
-- iCommandPlaneEmerTrimNoseDn	1102
-- iCommandPlaneLeftMFD_OSB10	651
-- iOculusRiftYaw	2144
-- iCommandPlaneDown	186
-- iCommandPlaneCircuitBreaker_26	1140
-- iCommand_FuelSysInterf_FuelQuantityIndTestOn	909
-- iCommandPlaneCircuitBreaker_12	1126
-- iCommandViewAWACSMapEventFlags	2119
-- iCommandViewFromTo	185
-- iCommandPlaneShowKneeboard	1587
-- iCommandPlaneUFC_SEL_UP	1318
-- iCommandCockpitCursorVertical	2037
-- iCommandPlaneLeftRudderStart	201
-- iCommandPlane_ILS_Volume_Decrease	1443
-- iCommandThrottle2Increase	1038
-- iCommandPlane_I251_Background_WhiteBlack	846
-- iCommandPlane_TACAN_Mode_Off	1425
-- iCommandPlaneRouteAutopilot	429
-- iCommandViewSlowDown	160
-- iCommandPlaneUHF01MhzSelectorDec	1210
-- iCommandPlaneFormationLights	521
-- iCommandInfoOnOff	152
-- iCommandViewPitCameraMoveDown	485
-- deviceName	Keyboard
-- iCommandPlane_AAP_SteerSw_Up	1423
-- iCommandPlane_SpotLight_hor_stop	380
-- iCommandPlaneCoverMySix	119
-- iCommandPlane_ABRIS_BT_2	497
-- iCommandAutoLockOnNearestSurfaceTarget	276
-- iCommandPlaneStabHorizon	388
-- iCommandPlaneThrottleFrictionDec	1069
-- iCommandPlaneAutopilot	62
-- iCommandPlaneCDU_LSK_9L	1231
-- iCommandAltimeterPressureIncrease	316
-- iCommand_IlluminationInterf_ADI_AHR_Illumination_brightness_down	941
-- iCommandPlaneCircuitBreaker_3	1117
-- iCommand_VMS_ALMAZ_UP_SpeechInfoOff	914
-- iCommandPlaneStabCancel	408
-- iCommandViewExternalZoomIn	334
-- iCommandPlane_ADF_Test	588
-- iCommandPlaneRightStop	200
-- iCommandPlaneTrimRightRudder	99
-- iCommandPlaneResetMasterWarning	144
-- iCommandPlane_ReadjustFreeTurbineRPM_Down	854
-- iCommandPlaneLeftMFD_OSB8_Off	989
-- iCommandViewCameraDownLeft	344
-- iCommandPlane_ADF_Channel_next	581
-- iCommandPlane_ABRIS_BT_5	500
-- iCommandPlaneLeftMFD_OSB1_Off	982
-- iCommandTrkEsc	55
-- iCommandPlaneFSSigAmplifier	1079
-- iCommandPlane_AutomaticTurn	526
-- iCommandEjectingSystemPower3	733
-- iCommandPlaneDLK_Target2	444
-- iCommandPlane_ABRIS_Axis_Increase	501
-- iCommandVehicle_LaunchGreenFlare	1614
-- iCommandSelecterDown	142
-- iCommandPlaneCircuitBreaker_7	1121
-- iCommandViewChase	12
-- iCommandPlane_R_800_50_100_switch	617
-- iCommandPlane_Env_MainAirSupply	1519
-- iCommandPlane_ABRIS_BT_2_up	806
-- iCommandPlaneNav_Airfields_off	872
-- iCommandHSI_Test	768
-- iCommandPlanePitchSASEngageR	1156
-- iCommandPlaneCMDDispenceStop	366
-- iCommandWeaponsBallisticSelectorRight	947
-- iCommandPlaneDLK_RefPoint_up	783
-- iCommandPlaneChangeRadarPRF	394
-- iCommandPlane_HOTAS_LeftThrottleButton	571
-- iCommandPlane_R_800_Emergency_Radio	619
-- iCommandCockpitIllumination	815
-- iCommandViewAWACSTargetZChanged	2129
-- iCommandViewAWACSChangeROE	2133
-- iCommandPlaneRightMFD_OSB12_Off	1018
-- iCommandPlaneADIAHRIllumination	813
-- iCommandPlaneLaunchPermissionOverride	349
-- iCommandPlane_VHF_AM_01MHz_Inc	1500
-- iCommandPlane_R_828_Channel_next	622
-- iCommandPlane_ILS_MHz_Increase	1440
-- iCommandPlaneCMSP_OSB_2	1325
-- iCommandPlayerCntrl	56
-- iCommandPlaneNav_Cancel	477
-- iCommandDecelerate	191
-- iCommandPlaneLeftMFD_OSB9	650
-- iCommandPlaneNavLights_CodeModeOff	520
-- iCommandPlaneEmerTrimRWingDn	1104
-- iCommandPowerOnOff	315
-- iCommandElectricalPowerInverterOFF	1075
-- iCommandPlaneSelecterVerticalAbs	2034
-- iCommandPlaneRightMFD_OSB9_Off	1015
-- iCommandPlane_R_800_4th_wheel_up	613
-- iCommandViewMirage	11
-- iCommandPlane_FLAPS_DN	1049
-- iCommandPlaneDLK_SendMemory	454
-- iCommandPlane_VHF_FM_025MHz_Inc	1480
-- iCommandPlane_ADF_Homer_change	580
-- iCommandPlane_Peak_Vol_Decrease	1457
-- iCommandViewUpLeft	208
-- iCommandPlaneLeftMFD_OSB14	655
-- iCommandPlaneChangeLock	100
-- iCommandViewForwardStop	291
-- iCommandSelecterStop	230
-- iCommandPlaneCDU_Y	1278
-- iCommandPlaneWheelParkingBrake	855
-- iCommandPlane_FLAPS_MNR	1048
-- iCommandActiveJamming	136
-- iCommandViewFastKeyboard	331
-- iCommandHelicopter_PPR_button_K	590
-- iCommandPlaneCDU_PNT	1252
-- iCommandPlaneCDU_3	1244
-- iCommandPlaneShipTakeOff	120
-- iCommandPlaneCDU_MINUS	1294
-- iCommandPlaneNavChangePanelModeLeft	456
-- iCommandPlaneDesignate_CageOn	439
-- iCommandPlaneNav_PB8	467
-- iCommand_VMS_ALMAZ_UP_Repeat	915
-- iCommandPlaneUHF10MhzSelectorDec	1206
-- iCommandPlaneIntercomILSDecrease	1179
-- iCommandViewDownRightSlow	211
-- iCommand_CPT_MECH_VMG_HYDRO_EKRAN_Cover	891
-- iCommandPlaneFeedbackTrimmer	2035
-- iCommandViewSnapView5	401
-- iCommandPlaneRadarOnOff	86
-- iCommandEjectingSystemPower1	730
-- iCommandPlane_HOTAS_MIC_SwitchRight	575
-- iCommandPlaneRightMFD_OSB6_Off	1012
-- iCommandPlaneCDU_FA	1286
-- iCommandPlane_I251_Brightness_Up	842
-- iCommandPlane_ABRIS_BT_1	496
-- iCommandPlaneFormationLightsDecrease	1359
-- iCommandHelicopter_CollectiveStopper_Up	856
-- iCommandCockpitTakeControl	248
-- iCommandADI_ZeroPitchTrimLeft	771
-- iCommandViewAWACSDistanceX1	2070
-- iCommandLandDetailsDecrease	138
-- iCommand_FireDetectorsTest1stGroup	954
-- iCommand_FireExting_ExtinguishersToDown	925
-- iCommandPlane_VHF_AM_Mode_EMERFM	1483
-- iCommandRecordCursorOnOff	307
-- iCommandLeftEngineFuelValveShutOff	722
-- iCommandPlaneCircuitBreaker_25	1139
-- defaultDeviceAssignmentFor	function: 000000002A965060
-- iCommandMainHydraulics	736
-- external_profile	function: 000000002B0FD1E0
-- iCommandKeyMaximum	2150
-- iCommandHelicopter_Rotor_Anti_Icing_System	818
-- filename	./Config/Input/Aircrafts/Default/keyboard/default.lua
-- iCommandHeadingMethodSwitch	745
-- folder	./Config/Input/Aircrafts/Default/keyboard/
-- iCommand_ExplorationStart	1616
-- iCommandCockpitDeviceCommandsEnd	3999
-- iCommandPlaneCircuitBreaker_8	1122
-- iCommandToggleCommandMenu	179
-- iCommandCockpitDeviceCommandsStart	3000
-- iCommandPlaneModeFI0	110
-- iCommandUpPilon	3
-- iCommandPlaneFSQuantityIndicatorSelectorEXTCTR	1096
-- iCommandViewAWACSClearDistance	436
-- iCommandPlaneSAUHRadio	60
-- iOculusRiftHeadPosZ	2149
-- iCommandPlaneModeBore	108
-- iCommandViewUpLeftSlow	213
-- iCommandWheelBrake	2101
-- iCommandPlaneFuelOn	79
-- iCommandPlane_L_ENG_FUEL_FLOW_Override	1064
-- iOculusRiftHeadPosY	2148
-- iCommandPlane_Oxygen_Normal	1504
-- iCommandPlaneStabHbarHeading	636
-- iOculusRiftPitch	2145
-- iCommandPlaneTrimPitch	2019
-- iCommandPlaneRightMFD_OSB12	683
-- iServiceInformAboutUserHAngle	2142
-- iCommandEjectingSystemPower1Cover	731
-- iCommandPlaneLeftMFD_OSB3	644
-- iCommandIncreaseRadarScanArea	263
-- iCommandViewAWACSInfoAddTargetButton	2140
-- iCommandViewAWACSJump	432
-- iCommandPlaneAHCPCICUOnOff	1389
-- iCommandPlaneCMSC_BRT_DEC	1349
-- iCommandPlaneLeftMFD_OSB19	660
-- iCommandViewAWACSShowHealths	2139
-- iCommandPlaneUFC_HACK	1306
-- iCommandViewLaserCodeChanged	2137
-- iCommandPlaneTrimStop	215
-- iCommandPlaneAUTDecreaseRegimeRight	168
-- iCommandHSI_CourseRotaryRight	765
-- iCommandViewDownLeftSlow	212
-- iCommandPlaneUHFSquelch	1226
-- iCommandPlaneIntercomUHFPress	1172
-- iCommandPlaneRightMFD_BRTMODE_DAY	1532
-- iCommandPlaneThreatWarnSoundVolumeUp	410
-- iCommandPlaneFloodLightsDecrease	1370
-- iCommandPlaneNav_CourseTimeRange	480
-- iCommandElectricalPowerInverterTEST	1076
-- iCommandViewAWACSChangeAlarmState	2134
-- iCommandAdjustViewAngleToComfortValue	2132
-- iCommandChangeRippleIntervalDown	308
-- iCommandPlaneLeftMFD_SYM_Stop	1006
-- iCommandPlaneNav_INU_normal_align	474
-- iCommand_TDC_AbsolutePositionHorizontal	2130
-- iCommandViewAWACSTargetXChanged	2128
-- iCommandPlaneThrustLeft	2005
-- iCommandHelicopter_Rotor_Anti_Icing_Dust_Protection_System	912
-- iCommandPlaneRightMFD_BRT_Stop	1029
-- iCommandPlaneNavSetFixtakingMode	457
-- iCommandDebugAxis10	2097
-- iCommandPlaneRadarDown	91
-- iCommandPlane_VHF_FM_Preset_Dec	1471
-- iCommandPlaneLeftMFD_OSB20	661
-- iCommandRotateMinus	2
-- iCommandViewAWACSRoadPriorChanged	2125
-- iCommandViewAWACSShowTargets	2124
-- iCommandPlaneThrustCommon	2004
-- iCommandPlane_VHF_FM_10MHz_Dec	1473
-- iCommandViewAWACSKeyData	2122
-- iCommandSaveGame	255
-- iCommandViewAWACSKeyKey	2121
-- iCommandPlaneNav_POS_corrMode	471
-- iCommandViewAWACSKeyState	2120
-- iCommandPlaneAHCPGUNArm	1379
-- iCommandUHFAntennaUpper	1553
-- iCommandViewTerrainLock	184
-- iCommandPlaneTrimLeft	93
-- iCommandPlane_HOTAS_SpeedBrakeSwitchCenter	579
-- iCommandViewAWACSMapEventX	2117
-- iCommandHelicopter_PPR_button_T	592
-- iCommandViewAWACSMapEventType	2116
-- iCommandHelicopterRotorEngineBrake_ByAxis	2100
-- iCommandViewBackSlowStop	290
-- iCommandPlane_R_800_3rd_wheel_up	611
-- iCommandViewAWACSTargetSetButton	2114
-- iCommandRightWheelBrake	2113
-- iCommandViewAWACS	15
-- iCommandViewAWACSChangeColumnForm	2111
-- iCommandPlane_ChangeDeliveryMode_right	530
-- iCommandViewAWACSChangeColumnState	2110
-- iCommandViewAWACSSetColumnSpeed	2109
-- iCommandPlane_ABRIS_BT_1_up	805
-- iCommandGSelectFeedSlot2	1623
-- iCommandPlaneAccelCompLights	1369
-- iCommandRALT_DangerousAltitudeRotaryLeft	776
-- iCommandPlanePositionLightsSteady	1358
-- iCommandViewAWACSUpdateWOInfoHigh	2107
-- iCommandViewAWACSUpdateWOInfoLow	2106
-- iCommandViewAWACSSetPathCloseButton	2105
-- iCommandPlaneDLK_Target3	445
-- iCommandPlaneCDU_4	1245
-- iCommand_AGR_axis_right	935
-- iCommandPlaneLeftMFD_OSB12	653
-- iCommandPlaneLeftMFD_BRT_Stop	1004
-- iCommandPlane_HOTAS_TriggerSecondStage_Off	638
-- iCommandPlane_VHF_AM_Tone	1491
-- iCommandViewBackStop	292
-- iCommandViewAWACSCancelColumnPath	2103
-- iCommandPlane_HOTAS_ChinaHatForward	566
-- iCommandPlaneAutopilotOverrideOn	427
-- iCommandPlaneAntiCollisionLights	518
-- iCommandPlaneFSQuantityIndicatorTest	1097
-- iCommandViewAWACSDistance	2065
-- iCommandPlaneCDU_PGDN	1290
-- iCommandPlaneRightMFD_DSP_Decrease	695
-- iCommandViewSaveAngles	236
-- iCommandRoleCoalitionUpdated	2115
-- iCommandHelicopterRightEngineBrake_ByAxis	2099
-- iCommandPlaneModeBVR	106
-- iCommandTargetingNavigationSystemsPower	740
-- iCommandPlaneNav_PB7_off	865
-- iCommandPlaneCDU_C	1256
-- iCommandPlane_R_800_Test_up	793
-- iCommandElectronicControlSystemLeftEngineCover	742
-- iCommandViewAWACSFireEnabledChanged	2127
-- iCommandViewTargetType	426
-- iCommandViewSnapView7	403
-- iCommandPlane_R_ENG_OPER_Norm	1061
-- iCommandViewBackSlow	40
-- iCommandDebugAxis8	2095
-- iCommandPlane_VHF_AM_Load	1492
-- iCommandPlaneRightMFD_OSB1	672
-- iCommandPlane_AutomaticTracking_Gunsight_switch	524
-- iCommandPlaneCircuitBreaker_34	1148
-- iCommandDebugAxis6	2093
-- iCommandDebugAxis5	2092
-- iCommandDebugAxis4	2091
-- iCommandDebugAxis3	2090
-- iCommandDebugAxis2	2089
-- iCommandPlane_AirborneTarget	528
-- iCommandViewExternalZoomInStop	335
-- iCommandPlane_SpotLight_up	513
-- iCommandPlaneCMSC_MWS	1348
-- iCommandPlaneJettisonFuelTanks	178
-- iCommandPlaneRightMFD_OSB14_Off	1020
-- iCommandPlaneLeftMFD_SYM_Dn	671
-- iCommandPlane_HOTAS_CMS_Left	558
-- iCommandPlaneAuxInstLightsDecrease	1364
-- iCommandPlaneCollective	2087
-- iCommandViewAWACSTargetRounds	2086
-- iCommandPlane_EAC_OFF	1051
-- iCommandHSI_Test_up	769
-- iCommandViewAWACSTargetCloseButton	2083
-- iCommandPlaneRightMFD_CON_Decrease	699
-- iCommandPlaneRightRudderStart	203
-- iCommandLampsControl_up	800
-- iCommandViewAWACSMapEventY	2118
-- iCommandPlaneTrimViewOnOff	174
-- iCommandPlaneCDU_2	1243
-- iCommandPlaneCollectiveDecrease	632
-- iCommandViewAWACSTargetFireButton	2081
-- iCommandViewAWACSInfoCloseButton	2080
-- iCommandViewAWACSInfoTargetButton	2079
-- iCommandPlaneLeftMFD_OSB4_Off	985
-- iCommandPlaneCircuitBreaker_10	1124
-- iCommandPlane_HOTAS_TDC_depress_off	635
-- iCommandPlaneNMSP_STRPT	1402
-- iCommandViewTempCockpitOn	17
-- iCommandViewAWACSTargetPointerY	2077
-- iCommandPlane_APU_Start	1055
-- iCommandViewAWACSTargetPointerX	2076
-- iCommandPlaneLeftRudderStop	202
-- iCommandCockpitVirtualAxisAbs	2075
-- iCommand_IlluminationInterf_Control_Panel_Illumination	894
-- iCommandGViewWSCenter	1607
-- iCommandViewBtn3Up	1600
-- iCommandEasyRadarOnOff	271
-- iCommandPlaneCircuitBreaker_31	1145
-- iCommandPlaneEngInstLightsIncrease	1362
-- iCommandThrottle1Increase	1035
-- iCommandPlaneMasterCautionOff	379
-- iCommandViewAWACSCenterOnPlane	2069
-- iCommandViewAWACSDangerousAreas	2068
-- iCommandNull	0
-- iCommandViewAWACSDetectionAreas	2067
-- iCommandViewTowerJump	298
-- iCommandViewAWACSLabels	2066
-- iCommandViewAWACSSetColumnPath	2102
-- iCommandViewAWACSZoomOut	2064
-- iCommandViewAWACSZoomIn	2063
-- iCommandViewAWACSZoom100	2062
-- iCommandViewAWACSLastZoomY2	2061
-- iCommandPlaneCMSP_RTN	1330
-- iCommandAutopilotEmergOFF_up	297
-- iCommandPlaneCircuitBreaker_23	1137
-- iCommandViewAWACSLastZoomX1	2058
-- iCommandViewAWACSMouseMoveY	2057
-- iCommandPlaneUFC_3	1297
-- iCommandPlaneAHCPLaserSafe	1381
-- iCommandViewDownLeft	207
-- iCommandPlaneLeftMFD_OSB3_Off	984
-- iCommandPlane_HOTAS_DataManagementSwitchOff	553
-- iCommand_FireExting_ExtinguishersCover	926
-- iCommandSelecterDownLeft	228
-- iCommandPlaneAUTOnOff	63
-- iCommandRotorRPMHigh	763
-- iCommandPlaneAUTDecreaseRight	164
-- iCommandViewAWACSMouseMoveX	2056
-- iCommandPlaneEmerTrimLWingDn	1103
-- iCommandViewAWACSDistanceToolDistance	2054
-- iCommandInfoTextOnOff	153
-- iCommandPlaneUFC_9	1303
-- iCommandViewAWACSMapMouseMove	2042
-- iCommandViewHorTransAbs	2049
-- iCommandPlane_R_800_Power_on_off	621
-- iCommandPlaneUHFPanelCover	1227
-- iCommandHelicopter_Engines_Anti_Icing_Dust_Protection_System	819
-- iCommandViewRollAbs	2047
-- iCommandPlane_AAP_SteerSw_Down	1424
-- iCommandViewRightMirrorOff	126
-- iCommandViewRight	29
-- iCommandPlaneDLK_Wingman2	448
-- ICommandMenuItem10	975
-- iCommandPlaneUnlockPadlock	330
-- iCommandPlane_ABRIS_Axis_Decrease_up	811
-- iCommandViewAWACSObjectIdHigh	2045
-- iCommandViewAWACSObjectIdLow	2044
-- iCommandPlane_Oxygen_Supply	1506
-- iCommandNoAcceleration	246
-- iCommandViewVertTransAbs	2051
-- iCommandViewFightGround	341
-- iCommandFuelBypassValveCover	729
-- iCommandPlaneBase_DistanceAbs	2041
-- iCommandHelicopter_Engine_Temperature_Control	822
-- iCommandHelicopter_Selected_Engine_interrupt_start	597
-- iCommandPlaneBase_Distance	2040
-- iCommandCockpitCursorHorizontalAbs	2038
-- iCommandHUDTest	748
-- iCommandAccelerate	53
-- iCommandPlaneEmerFlightControl	1114
-- iCommandViewCameraUpRightSlow	354
-- iCommandPlaneRightMFD_OSB15	686
-- iCommandPlaneCDU_H	1261
-- iCommandPlaneCDU_SYS	1236
-- iCommandPlaneLockPadlock	329
-- iCommandPlaneIntercomUHFDecrease	1170
-- iCommandPlaneMFDZoomAbs	2030
-- iCommandPlaneMFDZoom	2029
-- iCommandPlaneRadarVerticalAbs	2028
-- iCommandPointOfViewDownRight	219
-- iCommandPlane_TACAN_Mode_AAREC	1428
-- iCommandPlaneRadarVertical	2026
-- iCommandPlane_ABRIS_Axis_Push	503
-- iCommandPlane_Env_FlowLevel_Increase	1521
-- ICommandMenuItem3	968
-- iCommandGZoomNormal	1577
-- iCommandPlaneRadarHorizontal	2025
-- iCommandHelicopter_PPR_BAR_RV	595
-- iCommandPlanePickleOff	351
-- iCommandPlaneTrimRollAbs	2023
-- iCommandViewGround	10
-- iCommandPlaneDLK_All_up	788
-- iCommandPlaneTrimPitchAbs	2022
-- iCommandCockpitVirtualAxis	2074
-- iServiceInformAboutUserVAngle	2143
-- iCommandPlaneRefuelStatusIndLTSDecrease	1192
-- iCommandPlane_HOTAS_ChinaHatAft	567
-- iCommandAWACSHomeBearing	267
-- iCommandPlane_TACAN_Chanel_Tens_Increase	1435
-- iCommandPlaneTrimRoll	2020
-- iCommandPlaneCDU_PGUP	1289
-- iCommandPlaneRollDelta	2014
-- iCommandSelecterUpLeft	229
-- iCommandViewFriends	23
-- iCommandBatteryPower	1073
-- iCommandPlaneUHFStatus	1214
-- iCommandPlaneNav_PB1	460
-- iCommandPlane_Oxygen_100Oxygen	1507
-- iCommandPlaneIntercomUHFIncrease	1171
-- iCommandViewHorizontalAbs	2010
-- iCommandPlaneZoomView	2009
-- iCommandPlaneViewVertical	2008
-- iCommandPlaneThrustRight	2006
-- iCommandViewLndgOfficer	131
-- iCommand_ENG_INTERF_TempIndTestwRunningEng	907
-- iCommandTrainingUserResponded	1535
-- iCommandPlane_CallHelpWindow	852
-- iCommandPlaneUFC_4	1298
-- iCommandPlaneNav_PB9_off	867
-- iCommandPlanePitch	2001
-- iCommandHSI_HeadingRotaryLeft	766
-- iCommandPlanePositionLightsFlash	1356
-- iCommandMaximum	1638
-- iCommandPlaneCMSC_UNK	1355
-- iCommandPlane_TACAN_Chanel_XY_Mode	1436
-- iCommandPlaneModeVS	107
-- iCommandPlaneImmortal	169
-- iCommandSensorReset	1635
-- iCommandExternalCargoAutounhook	1634
-- iCommandPlaneCDU_S	1272
-- iCommandViewSaveAngles3	238
-- iCommandLaserRangeModeSwitch	887
-- iCommandPlane_HARS_HDG_Decrease	1453
-- iCommandPlane_R_828_ASU	625
-- iCommandPlaneAHCPMasterSafe	1375
-- iCommandPlane_R_ENG_OPER_Ign	1060
-- iCommandClockElapsedTimeReset	1629
-- iCommandDVADRFunctionSTDBY	1544
-- ICommandSwitchToCommonDialog	980
-- iCommandViewLeft	28
-- iCommandViewSlowKeyboard	332
-- iCommandPlaneLeftMFD_OSB12_Off	993
-- iCommandToggleReceiveMode	1626
-- iCommandToggleMirrors	1625
-- iCommandViewCockpitSetPilotSeat	1603
-- iCommandTakeControlTrack	1621
-- iCommandGZoomUpdate	1620
-- iCommandFriendlyChat	50
-- iCommandScoresWindowToggle	360
-- iCommandViewNVGOff	1619
-- iCommand_ExplorationCansel	1618
-- iCommand_ExplorationTargetSelection	1617
-- iCommandRepKeyBegin	4000
-- iCommandVehicle_LaunchWhiteFlare	1615
-- iCommandVehicle_LaunchRedFlare	1613
-- ICommandMenuItem4	969
-- iCommandWeaponsControlSystemCover	735
-- iCommandViewNVG_GainDown	1612
-- iCommandViewLeftMirrorOff	128
-- iCommandPlaneCDU_V	1275
-- iCommandPlane_P_51_WarEmergencyPower	1601
-- iCommandPlane_HOTAS_CoolieLeft	541
-- iCommandViewNVG_GainUp	1611
-- iCommandActivePauseOnOff	816
-- iCommandPlaneNav_INU_realign_off	869
-- iCommandPlaneCircuitBreaker_9	1123
-- iCommandPlane_HOTAS_DataManagementSwitchDown	550
-- iCommandPlaneDLK_mode_change	641
-- iCommandViewForwardSlow	39
-- iCommandViewNVGOnOff	416
-- iCommandPowerGeneratorLeft	711
-- iCommandViewPauseOnOff	1609
-- ICommandToggleConsole	981
-- iCommandPlane_LaserCode_Previous	848
-- iCommandGStabilize	1608
-- ICommandMenuItem1	966
-- iCommandViewAWACSDistanceY2	2073
-- iCommandPlaneFSQuantityIndicatorSelectorEXTWING	1095
-- iCommandViewCockpitSetOperatorSeat	1604
-- iCommandPlanePackWing	70
-- iCommandGSelectFeedSlot1	1622
-- iCommandPlaneDLK_Wingman4	450
-- iCommandPlane_ABRIS_BT_4	499
-- iCommandViewCockpitChangeSeat	1602
-- iCommandPlane_STALL_Vol_Decrease	1455
-- iCommandPlaneFSExtTanksWingValve	1077
-- iCommandPlaneAHCPGUNPACArm	1377
-- iCommandPlaneJoinUp	117
-- iCommandPromotePlane	287
-- iCommandViewFree	16
-- iCommandPlaneUHFFreqModeDialPRESET	1223
-- iCommandThreatMissilePadlock	258
-- iCommandPlane_SPU9_PTT_on	1589
-- iCommandTrackEditReplace	319
-- iCommandViewCameraReturn	347
-- iCommandViewRightSlow	33
-- iCommandPlaneDLK_Erase	452
-- iCommandViewBtn1Down	1595
-- iCommandPlaneNav_PB0_off	858
-- iCommandViewTransposeModeOff	1594
-- iCommandPlaneTrimLeftRudder	98
-- iCommandViewTransposeModeOn	1593
-- iCommandPlaneLeftMFD_OSB11_Off	992
-- iCommandPlane_P_51_PTT_off	1592
-- iCommandPlaneCDU_LSK_3R	1232
-- iCommand_WEAP_INTERF_MasterSimulate	890
-- iCommandViewCameraRightSlow	46
-- iCommandPlaneLeftMFD_BRT_Decrease	667
-- iCommandPlane_SPU9_PTT_off	1590
-- iCommandPlane_ILS_KHz_Increase	1442
-- iCommandPlane_AAP_SteerPt_MARK	1421
-- iCommandGIsometricView	1588
-- iCommandPlaneChangeWeapon	101
-- iCommandFuelmeterPower	721
-- iCommandViewParticleEffect	1586
-- iCommandAutoLockOnCenterSurfaceTarget	277
-- iCommandViewSmoke2	1045
-- iCommandGHoldCursorModeOn	1584
-- iCommandGChangeLN	1572
-- iCommandPlane_TACAN_Chanel_Ones_Increase	1433
-- iCommandGLockoff	1581
-- iCommandPlaneCircuitBreaker_24	1138
-- iCommandGChangeSpeedV	1579
-- iCommandViewExplosion	27
-- iCommand_PVI_BRIGHTNESS_LEVER_down	920
-- iCommandGZoomIn	1576
-- iCommandGFireStop	1575
-- iCommandPlane_HOTAS_MIC_SwitchOff	576
-- iCommandPlaneDLK_Wingman3_up	786
-- iCommandPlaneRadarUpLeft	234
-- iCommandGReloadWeapon	1573
-- iCommandViewAir	8
-- iCommandPlaneTrimOn	957
-- iCommandGGroupModeOff	1583
-- iCommandPlane_SpotLight_right	512
-- iCommandPlaneDLK_Ingress_up	790
-- iCommandPlaneNav_PB6	465
-- iCommandGChangeWS	1571
-- iCommandPlane_APU_Off	1056
-- iCommandPlaneNMSP_TCN	1404
-- iCommandHelicopterHover_up	385
-- iCommandPlane_FLAPS_MNR_from_DN	1569
-- iCommandPlane_VHF_FM_FreqMode_OFF	1465
-- iCommandPlaneCircuitBreaker_30	1144
-- iCommandPlaneRightRudderStop	204
-- iCommandPlane_HOTAS_CMS_Zaxis	1041
-- iCommandPlaneNav_PB7	466
-- iCommandViewCameraCenter	49
-- iCommandEmergencyGear	750
-- iCommandPlaneStabPathHold	637
-- iCommandMechClock_LeftLever_TurnRight	756
-- iCommandPlane_R_ENG_OPER_Norm_from_Ign	1567
-- ICommandMenuItem9	974
-- iCommandPlane_L_ENG_OPER_Norm_from_Ign	1566
-- iCommandPlane_R_ENG_OPER_Norm_from_Motor	1565
-- iCommandPlane_HOTAS_CoolieOff	543
-- iCommandPlane_L_ENG_OPER_Norm_from_Motor	1564
-- iCommandPlaneRightMFD_OSB5	676
-- iCommand_LASTE_from_PATH_to_ALTHDG	1562
-- iCommandPlane_R_800_3rd_wheel_down	612
-- iCommandPlaneCDU_5	1246
-- iCommandPlaneCircuitBreaker_13	1127
-- iCommandGraphicsFrameRate	157
-- iCommandPlaneRightMFD_SYM_Dn	701
-- iCommandViewSaveAngles7	242
-- ICommandSwitchDialog	979
-- iCommandRWRIntensityIncrease	1559
-- iCommandPlaneLeftMFD_OSB4	645
-- iCommandPlaneIncreaseBase_Distance	412
-- iCommandRWRIntensityDecrease	1558
-- iCommandPointOfViewDown	220
-- iCommandPlane_HOTAS_LeftThrottleButton_Off	1557
-- iCommandPlaneJettisonFuelTanksUp	170
-- iCommandPlane_ILS_Power	1438
-- iCommandUHFAntennaLower	1555
-- iCommandUHFAntennaAuto	1554
-- iCommandViewAWACSTargetRemoveButton	2082
-- iCommandPlaneRightMFD_OSB18_Off	1024
-- iCommandIFFAntennaBoth	1551
-- iCommandViewAWACSUnitInfoOff	424
-- iCommandPlane_LockOn_start	509
-- iCommandIFFAntennaUpper	1550
-- iCommandCanopyJettisonUnlockButton	1549
-- iCommand_FireExting_Discharge_Left	1407
-- iCommandPlane_Env_TempPress_RAM	1518
-- iCommandPlaneDLK_Wingman1	447
-- iCommandCanopyActuatorDisengage	1547
-- iCommandPlaneDecreaseBase_Distance	413
-- iCommandADI_TestCover	775
-- iCommandPlaneDownStart	195
-- iCommandViewAWACSShowPathes	2123
-- iCommandPlaneLeftMFD_ADJ_Decrease	663
-- iCommandDVADRFunctionREC	1545
-- iCommandPlaneChangeLockUp	1627
-- iCommandViewPitCameraMoveCenter	491
-- iCommandDVADRFunctionOff	1543
-- iCommand_AGR_Test	932
-- iCommandViewCameraUpSlow	47
-- ICommandMenuItem7	972
-- iCommandPlaneAUTDecreaseLeft	162
-- iCommandPlane_Altimeter_PNEU	1411
-- iCommandArmGroundSafetySwitch	1542
-- iCommandPlane_Altimeter_CENTER	1413
-- iCommandPlaneRightMFD_OSB3	674
-- iCommandPlane_VHF_FM_Tone	1469
-- iCommandPlaneLeftMFD_OSB7_Off	988
-- iCommandPlaneIntercomIFFPress	1178
-- iCommandExtLadderButton	1539
-- iCommandPlane_HARS_MagneticVar_Null	1450
-- iCommandPlaneRightMFD_BRT_Decrease	697
-- iCommandPlane_SpotLight_vert_stop	515
-- iCommandPlaneCDU_K	1264
-- iCommandViewBriefing	1536
-- iCommandPlaneRudder	2003
-- iCommandPlaneRightMFD_DSP_Increase	694
-- iCommandPlane_Env_CanopyDefog_Dec	1510
-- iCommandPlaneLockPadlockTerrain	1534
-- iCommand_ENG_INTERF_TempIndTestwStoppedEng	908
-- iCommandPlaneEject	83
-- iCommandPlaneCMSP_MWS_ON	1335
-- iCommand_UV26_BITCover	898
-- iCommandViewFreeJump	158
-- iCommandPlaneCMDDispenceOff	365
-- iCommandPlaneNightVisionLTSALL	1195
-- iCommandPlaneGear	68
-- iCommandPlaneRightMFD_BRTMODE_OFF	1530
-- iCommandPlane_AAP_PageSel_POSITION	1417
-- iCommandPlaneCDU_T	1273
-- iCommandPlaneAirBrakeOn	147
-- iCommandViewRightMirrorOn	125
-- iCommandFuelExternalPumpsTanksOuter	720
-- iCommandPlaneCMSP_JTSN	1331
-- iCommandPlaneNav_Airfields	473
-- iCommandPlaneFSRightMainBoostPump	1088
-- iCommandPlaneUpStart	193
-- iCommandPlaneLeftMFD_BRTMODE_DAY	1529
-- iCommandViewLongitudeTrans	2052
-- iCommandHelicopter_Rotor_Lock	605
-- iCommandPlaneTrimOff	958
-- iCommandPlaneUFC_6	1300
-- iCommandPlane_VHF_AM_025MHz_Dec	1501
-- iCommandPlaneLeftMFD_BRTMODE_OFF	1527
-- iCommandPlaneAHCPAltSCERadar	1386
-- iCommandPlaneNav_PB4_off	862
-- iCommandPlane_Env_TempLevel_Increase	1526
-- iCommandFuelPumpsTankForward	717
-- iCommandPlane_Env_TempLevel_Decrease	1525
-- iCommandPlane_Env_AirConditioner_COLD	1524
-- iCommandHelicopter_PPR_button_H_up	302
-- iCommandPlane_Env_AirConditioner_HOT	1523
-- iCommandPlane_L_ENG_OPER_Norm	1058
-- iCommandGLaserRangerOn	1630
-- iCommand_TDC_AbsolutePositionVertical	2131
-- iCommandPlaneTrimDown	96
-- iCommandPlaneCobra	121
-- iCommandPlaneNightVisionLTSOFF	1196
-- iCommandPlaneDLK_Wingman4_up	787
-- iCommandPlane_Env_TempPress_NORM	1516
-- iCommandPlane_Env_BleddAir	1515
-- iCommand_C061K_heat	901
-- iCommandViewBtn2Up	1598
-- iCommandPlane_Env_WindshieldWash	1514
-- iCommandPlaneIntercomVHFPress	1169
-- iCommandFuelExternalPumpsTanksInner	719
-- iCommandViewBinocular	407
-- iCommandPlane_Env_CanopyDefog_Inc	1511
-- iCommandPlaneLeftMFD_OSB2	643
-- iCommandPlane_R_800_1st_wheel_down	608
-- iCommandPlane_VHF_FM_Mode_MAN	1463
-- iCommandPlaneRightMFD_ADJ_Stop	1027
-- iCommandViewCameraAltitude	2043
-- iCommandPlane_R_828_ASU_up	794
-- iCommand_FireExting_Reservoirs	928
-- iCommandPlaneLeftMFD_OSB17	658
-- iOculusRiftHeadPosX	2147
-- iCommandPlaneNav_PB5_off	863
-- iCommandSoundMicOff	124
-- iCommand_IlluminationInterf_Panels_Illumination_brightness_down	939
-- iCommandPlane_Oxygen_Emergency	1503
-- iCommandPlane_VHF_AM_025MHz_Inc	1502
-- iCommandPlane_VHF_AM_01MHz_Dec	1499
-- iCommandPlaneCMSP_DISP_ON	1341
-- iCommandPlaneNav_SelfCoord	479
-- iCommandPlane_HOTAS_DataManagementSwitchRight	552
-- iCommandPlaneUHFFunctionDialOFF	1218
-- iCommandPlaneDLK_None	945
-- iCommandPlaneNav_Steerpoints	469
-- iCommandPlane_HOTAS_TriggerFirstStage	555
-- iCommandPlane_VHF_AM_10MHz_Inc	1496
-- iCommandPlane_VHF_AM_Preset_Inc	1494
-- iCommandPlane_VHF_AM_Preset_Dec	1493
-- iCommandHUDBrightnessUp	746
-- iCommandPlane_VHF_AM_FreqMode_DN	1489
-- iCommandPlane_VHF_AM_FreqMode_TK	1488
-- iCommandPlaneFSQuantityIndicatorSelectorMAIN	1093
-- iCommandViewUpRightSlow	210
-- iCommandPlane_STALL_Vol_Increase	1456
-- iCommandPlane_R_828_volume_down	627
-- iCommandViewSaveAngles6	241
-- iCommandPlaneFlaps	72
-- iCommandPlaneRoll	2002
-- iCommandEmergencyGearCover	751
-- iCommandRALT_Test	778
-- iCommandBKOMode	761
-- iCommandChangeReleaseMode	284
-- iCommandPlaneUHF01MhzSelectorInc	1209
-- iCommandPlaneRightMFD_OSB1_Off	1007
-- iCommandPlane_VHF_AM_Mode_EMERAM	1484
-- iCommandPlaneCircuitBreaker_33	1147
-- join	function: 000000002A9650B0
-- iCommandPlaneRightMFD_OSB11_Off	1017
-- iCommandWeaponsBallisticSelectorLeft	948
-- iCommandPlane_VHF_AM_Volume_Dec	1481
-- iCommandPlaneUFC_INTEN_INCREASE	1322
-- iCommandPlane_VHF_FM_01MHz_Inc	1478
-- iCommandPlane_DescentMode	507
-- iCommandPlane_VHF_FM_1MHz_Inc	1476
-- iCommandPlane_VHF_FM_1MHz_Dec	1475
-- iCommandPlane_HOTAS_TDC_depress_on	634
-- iCommandPlaneIntercomHM	1187
-- iCommandAntiGSuitTest	1546
-- iCommandMechClock_RightLever_Rotate_right	760
-- iCommandPlane_HARS_SyncButton	1452
-- iCommandViewSnapViewStop	406
-- iCommandPlaneDLK_Target2_up	781
-- iCommandViewAWACSBridgesPriorChanged	2126
-- iCommandPlane_VHF_FM_Load	1470
-- iCommandPlaneCMDChangeBurstAmount	372
-- iCommandArmGroundSafetyCover	1541
-- iCommandPlane_VHF_FM_Squelch	1468
-- iCommand_AGR_Oriet	933
-- iCommandPlane_VHF_FM_FreqMode_TK	1466
-- iCommandViewSwitchReverse	180
-- iCommandHelicopter_SelectWeapon_hor_up	381
-- iCommandPlaneDLK_RefPoint	446
-- iCommandPlaneCockpitIlluminationPanels	493
-- iCommandPlane_R_800_1st_wheel_up	607
-- iCommandPlane_VHF_FM_Mode_PRE	1464
-- iCommandPlaneAttackMyTarget	118
-- iCommandPlane_Oxygen_Ind_Test	1508
-- iCommandPlane_VHF_FM_Mode_EMERAM	1462
-- iCommandPlaneTrimRudderAbs	2024
-- iCommandCockpitClickOff	362
-- iCommandPlane_P_51_PTT_on	1591
-- iCommandPlaneLeftMFD_OSB18_Off	999
-- iCommandPlane_HARS_HDG_Increase	1454
-- iCommandPlaneCMSP_MODE_AUTO	1346
-- iCommandPlane_EngageAirDefenses	522
-- iCommandMissileFire	5
-- iCommandExtLadderButtonCover	1538
-- iCommandPlaneCDU_I	1262
-- iCommandViewNightVisionGogglesOn	438
-- iCommandPlaneIntercomILSIncrease	1180
-- iCommandElectronicControlSystemLeftEngine	741
-- iCommandViewPitCameraMoveLeft	486
-- iCommandPlane_HARS_MagneticVar_Min15	1449
-- iCommandPlaneAHCPMasterArm	1374
-- iCommandPlane_HARS_HemisphereSel	1448
-- iCommandPlane_HARS_LAT_Correction_Increase	1447
-- iCommandPlaneUFC_1	1295
-- iCommandViewAWACSSetColumnAltitude	2138
-- iCommandPlaneDLK_Target1	443
-- iCommandPlane_ILS_KHz_Decrease	1441
-- iCommandEGI_HQ_TOD	1556
-- iCommandPlane_TACAN_Test	1437
-- iCommandViewInfoControlPanelOnOff	1637
-- iCommandPlaneCDU_NAV	1237
-- iCommandPlaneThrustLeftDelta	2017
-- iCommandPitotAoAHeat	910
-- iCommandPlaneDropFlareOnce	357
-- iCommandPlane_R_828_Power_on_off	628
-- iCommandPlane_TACAN_Chanel_Tens_Decrease	1434
-- iCommandGGroupModeOn	1582
-- iCommandPlane_HOTAS_PinkySwitchCenter	570
-- iCommandPlane_TACAN_Volume_Increase	1431
-- iCommandPlaneLightsOnOff	175
-- iCommandPlane_TACAN_Volume_Decrease	1430
-- iCommandPlaneDoAndBack	115
-- iCommandPlane_TACAN_Mode_AATR	1429
-- iCommandPlaneCMSP_RWR_MENU	1338
-- iCommandPlane_TACAN_Mode_Rec	1426
-- iCommandPlaneCMSP_NEXT_UP	1328
-- iCommandViewRoll	2046
-- iCommandPlaneCircuitBreaker_32	1146
-- iCommandPlane_AAP_SteerPt_MISSION	1422
-- iCommandQuit	51
-- iCommandPlane_DescentModeOff	508
-- iCommandViewLeftMirrorOn	127
-- iCommandPlaneRightMFD_SYM_Stop	1031
-- iCommandPlaneUHF100MhzSelector1	1201
-- iCommandPlane_AAP_SteerPt_FLTPLAN	1420
-- iCommandViewPitCameraMoveForward	488
-- iCommandPlane_HeadOnAspect_up	798
-- ICommandMenuExit	978
-- iCommandPlane_AAP_PageSel_STEER	1418
-- iCommandPlaneFSRightMainFillDisable	1090
-- iCommandPlane_AAP_PageSel_OTHER	1416
-- iCommandPlane_HOTAS_CoolieRight	542
-- iCommandViewAWACSDistanceX2	2072
-- iCommandPlaneLeftMFD_OSB7	648
-- iCommandPlaneFltInstLightsIncrease	1368
-- iCommandPlane_AAP_CDU_Power	1414
-- iCommandPlaneDropSnarOnce	176
-- iCommandPlane_Altimeter_ELECT	1412
-- iCommandPlane_HOTAS_TargetManagementSwitchLeft	546
-- iCommand_FireExting_Discharge_Right	1409
-- iCommandPlaneIntercomTCNDecrease	1182
-- iCommand_FireExting_Discharge_Center	1408
-- iCommandCockpitSecondClickOn	433
-- iCommandCanopyJettison	1548
-- iCommandPlaneLGPTaxiLight	1398
-- iCommandPlaneNMSP_ILS	1405
-- iCommandGViewAction	1570
-- iCommandPlaneNMSP_ANCHR	1403
-- iCommandPlaneNMSP_TISL	1401
-- iCommandViewDown	31
-- iCommandIFF_Power	738
-- iCommandHSI_HeadingRotaryRight	767
-- iCommandPlaneLeftMFD_OSB6	647
-- iCommandCockpitShowPilotOnOff	835
-- iCommandPlaneCDU_MK	1282
-- iCommandPlaneNMSP_HARS	1399
-- iCommandPlaneNMSP_PTR_ABLE_STOW	1406
-- iCommandPlaneLGPLightsOff	1397
-- iCommandPlaneNav_PB5	464
-- iCommandViewSmoke3	1046
-- iCommandPlaneLGPLandLight	1396
-- iCommandRightEngineFuelValveShutOffCover	725
-- iCommandPlaneUFC_8	1302
-- iCommandPlaneDropSnarOnceOff	536
-- iCommandPlane_HOTAS_CMS_Down	557
-- iCommandPlaneLGPAntiSkid	1394
-- iCommandPlaneUHFVolumeInc	1217
-- iCommandScreenShot	257
-- iCommandPlaneJump	192
-- iCommandGroundPowerDC	704
-- iCommandPlane_JettisonMode_explosion	850
-- iCommandPlaneAHCPIFFCCOn	1391
-- iCommandHelicopterHover	537
-- iCommand_C061K_power	900
-- iCommandDatalinkUHF_SA	716
-- iCommandPlaneLeftMFD_OSB15	656
-- iCommandPlaneAHCPJTRSOnOff	1390
-- iCommandPlaneAHCPHUDModeNormSTBY	1388
-- iCommandPlaneAHCPHUDModeDayNight	1387
-- iCommandPlaneAHCPAltSCEDelta	1385
-- iCommand_UV26_Power	897
-- iCommandPlane_R_800_4th_wheel_down	614
-- iCommandPlaneRadarLeft	88
-- iCommandPlaneFSLeftMainFillDisable	1089
-- iCommandPlaneAHCPLaserTrain	1382
-- iCommandPlaneAHCPLaserArm	1380
-- iCommandPlaneAHCPGUNSafe	1378
-- iCommandPlaneFSRefuelLigtingDecrease	1098
-- iCommandPlaneDropChaffOnce	358
-- iCommandPlane_Env_WindshieldCenter	1513
-- iCommandPlaneLeftMFD_OSB19_Off	1000
-- iCommandPlane_HOTAS_CMS_Off	560
-- iCommandPlane_Env_AirConditioner_AUTO	1522
-- iCommandViewAWACSVehControlCloseButton	2108
-- iCommandPlaneFltInstLightsDecrease	1367
-- iCommandPlaneCockpitIllumination	300
-- iCommandPlaneAuxInstLightsIncrease	1365
-- iCommandPlaneCMSP_NEXT_DOWN	1329
-- iCommandPlane_AAP_EGI_Power	1415
-- iCommandPlaneEngInstLightsDecrease	1361
-- iCommandPlaneFormationLightsIncrease	1360
-- iCommandPlanePositionLightsOff	1357
-- iCommandKeyNull	2000
-- iCommandPlaneCMSC_PRI	1353
-- iCommandPlaneCMSC_AUD_INC	1352
-- iCommandPlaneCMSC_AUD_DEC	1351
-- iCommandPlane_HARS_MagneticVar_Plus15	1451
-- iCommandHelicopter_Selected_Engine_interrupt_start_up	803
-- iCommandPlaneCMSP_MODE_SEMI	1345
-- iCommandPlaneUHFFunctionDialMAIN	1219
-- iCommandPlaneUFC_7	1301
-- iCommandPlane_VHF_AM_1MHz_Inc	1498
-- iCommandPlaneCMSP_DISP_MENU	1340
-- iCommandPlaneRightMFD_ADJ_Increase	692
-- iCommandHUDTest_up	749
-- iCommandRecordSubtitleOff	325
-- iCommandViewSaveAngles4	239
-- iCommandPlane_TACAN_Mode_TR	1427
-- iCommandUnfreezeActionSystem	294
-- iCommandPlane_HeadOnAspect	529
-- iCommandPlaneFSLineCheck	1080
-- iCommandPlaneStabHrad	390
-- iCommandPlaneCMSP_JMR_MENU	1336
-- iCommandPlaneDLK_SendMemory_up	791
-- iCommandPlaneCircuitBreaker_15	1129
-- iCommandViewExternalZoomOut	336
-- iCommandPlaneNoseIllum	1363
-- iCommandPlaneCMSP_OSB_3	1326
-- iCommandPlane_ShowControls	851
-- iCommandPlaneUFC_INTEN_DECREASE	1323
-- iCommandPlaneNav_Steerpoints_off	868
-- iCommandPlane_VHF_FM_025MHz_Dec	1479
-- iCommandPlane_K041_Power	525
-- iCommandPlane_LockOn_finish	510
-- iCommandViewAll	26
-- iCommandPlaneUFC_DATA_DOWN	1317
-- iCommandPlaneUFC_DATA_UP	1316
-- iCommandPlaneEmerPitchRollTrim	1101
-- iCommandPlaneNav_Wind_off	880
-- iCommandPlaneUFC_STEER_UP	1314
-- iCommandPlaneFSQuantityIndicatorSelectorINT	1092
-- iCommandPlaneUFC_MASTER_WARNING	1313
-- iCommandViewAWACSApplyTargetPointer	2078
-- iCommandPlaneCDU_U	1274
-- iCommandPlaneUFC_MK	1311
-- iCommandPlaneLeftMFD_OSB18	659
-- iCommandViewSnapView4	400
-- iCommandPlaneUFC_ENT	1310
-- iCommandPlaneLeftMFD_OSB15_Off	996
-- iCommandAutoLockOnCenterAircraft	273
-- iCommandViewRear	359
-- iCommandPlaneUFC_CLR	1309
-- iCommandPlaneUFC_LTR	1308
-- iCommandPlaneUFC_FUNC	1307
-- iCommandPlane_ILS_Volume_Increase	1444
-- iCommandPlaneUFC_SPC	1305
-- iCommandPlaneUFC_0	1304
-- iCommandPlaneNav_Enter	476
-- iCommandADI_Test_up	774
-- iCommandPlaneLeftMFD_BRTMODE_NIGHT	1528
-- iCommandPlane_AutomaticTurn_up	795
-- iCommandPlaneCMSP_MODE_MAN	1344
-- iCommandViewCameraDownRight	345
-- iCommandPlaneRightMFD_OSB11	682
-- iCommandPlaneUFC_2	1296
-- iCommandViewCameraUpLeft	342
-- iCommandPlane_HARS_LAT_Correction_Decrease	1446
-- iCommandThrottle1Decrease	1036
-- iCommandPlaneWheelBrakeOn	74
-- iCommandPlaneRudderDelta	2015
-- iCommandPlaneCDU_BRT	1288
-- iCommandPlaneCDU_CLR	1285
-- iCommandPlaneCDU_SPC	1284
-- iCommandPlaneCDU_BCK	1283
-- iCommandPlaneAUTDecreaseRegime	67
-- iCommandIFF_PowerCover	739
-- iCommandPlaneIntercomAIMDecrease	1173
-- iCommandPlaneCDU_X	1277
-- iCommandPlaneCDU_W	1276
-- iCommandPlane_ABRIS_Axis_Decrease	502
-- iCommandPlaneRadarRight	89
-- iCommandPlaneCDU_R	1271
-- iCommandMechClock_RightLever_Down_up	758
-- iCommandPlane_RouteMode	506
-- iCommandPlaneCDU_Q	1270
-- iCommandPlaneCDU_O	1268
-- iCommandRollBack	250
-- iCommandPlaneCDU_N	1267
-- iCommandPlaneCDU_M	1266
-- iCommandPlaneJettisonWeapons	82
-- iCommandPowerBattery1_Cover	707
-- iCommand_ZMS_3_MagVarRotaryRight	949
-- iCommandHSI_SteeringSelection	770
-- iCommandPlaneMasterCaution	252
-- iCommandGHoldCursorModeOff	1585
-- iCommandPlaneCDU_G	1260
-- iCommandPointOfViewUpLeft	223
-- iCommandPointOfViewRight	218
-- iCommandPlaneFonar	71
-- iCommandAutopilotEmergOFF	538
-- iCommandPlaneCDU_F	1259
-- iCommandPlaneFire	84
-- iCommandPlaneCMDChangeRippleQuantity	368
-- iCommandPlaneStabHbarBank	387
-- iCommandPlaneAHCPMasterTrain	1376
-- iCommandPlaneRightMFD_OSB2	673
-- iCommandPlaneCDU_D	1257
-- iCommandThrottle2Decrease	1039
-- iCommandPlaneCDU_B	1255
-- iCommandPlane_EAC_ARM	1050
-- iCommandPlaneCDU_A	1254
-- iCommandPlaneCDU_SLASH	1253
-- iCommandPlaneUHFTTone	1225
-- iCommandPlaneIntercomILSPress	1181
-- iCommandViewCameraDownRightSlow	356
-- iCommandPlaneUHF1MhzSelectorDec	1208
-- iCommandPlaneIntercomVolumeIncrease	1186
-- iCommandPlaneCDU_8	1249
-- iCommandPlane_HOTAS_CMS_Right	559
-- iCommandHelicopter_SelectWeapon_Internal	824
-- iCommandPlaneCDU_7	1248
-- iCommandPlaneNavLights_CodeModeOn	519
-- iCommandHSI_CourseRotaryLeft	764
-- iCommandCockpitClickOn	361
-- iCommandViewPlaneAndGround	134
-- iCommandViewLaserChangeCode	1561
-- iCommandViewAWACSInfoPathButton	2104
-- iCommandPlane_ADF_Mode_change	583
-- iCommandPlaneCDU_1	1242
-- iCommandPlaneCDU_PREV	1241
-- iCommandViewFastMouse	321
-- iCommand_IlluminationInterf_Cockpit_Night_Illumination_brightness_down	937
-- iCommandPlaneNavChangePanelModeRight	455
-- iCommandPlaneSASMonitorTestRight	1159
-- iCommandPlaneRightMFD_OSB16	687
-- iCommandPlaneNav_INU_precise_align_off	871
-- iCommandPlaneCDU_OSET	1239
-- iCommandPlaneCircuitBreaker_35	1149
-- iCommandPlaneSelecterHorizontalAbs	2033
-- iCommand_UV26_BIT	899
-- iCommandPlaneCDU_LSK_5R	1233
-- iCommandPlaneCMDDispence	364
-- iCommandPlane_VHF_FM_Volume_Inc	1460
-- iCommandDatalinkTLK	714
-- ICommandMenuItem11	976
-- iCommandHelicopter_PPR_button_DIR	594
-- iCommandPlaneCDU_LSK_7L	1230
-- iCommandLeftEngineStop	313
-- iCommandViewSlowMouse	322
-- iCommandPlaneCDU_LSK_3L	1228
-- iCommandViewAWACSTargetRadiusSet	2136
-- iCommandAltimeterPressureStop	318
-- iCommandPlaneCDU_0	1251
-- iCommandViewBtn2Down	1597
-- iCommandPlaneUHFFreqModeDialMNL	1222
-- iCommandPlaneLevitation	959
-- iCommandPlaneUHFPresetChannelSelectorDec	1200
-- iCommandPlaneUHFFunctionDialBOTH	1220
-- iCommandPlaneFormation	116
-- iCommandPlaneAHCPIFFCCTest	1392
-- iCommandPlaneRightMFD_DSP_Stop	1028
-- iCommandPlaneUHFLoad	1215
-- iCommandViewZoomAbs	2012
-- iCommandPlaneCircuitBreaker_27	1141
-- iCommandPointOfViewLeft	222
-- iCommandPlaneUFC_DEPR_DOWN	1321
-- iCommandPlane_ChangeDeliveryMode_left	531
-- iCommandPlaneUHF1MhzSelectorInc	1207
-- iCommandPlaneAUTIncreaseRight	163
-- ICommandMenuItem8	973
-- iCommandPlaneUHF10MhzSelectorInc	1205
-- iCommandPlaneUHF100MhzSelectorA	1204
-- iCommandPlaneUHF100MhzSelector3	1203
-- iCommandPlane_L_ENG_OPER_Motor	1059
-- iCommandPlane_HOTAS_BoatSwitchCenter	565
-- iCommandPlaneCircuitBreaker_36	1150
-- iCommandPlaneUHFPresetChannelSelectorInc	1199
-- iCommandPlaneFireDetectBleedAirTest	1198
-- iCommandViewWeaponAndTarget	135
-- iCommandMechClock_LeftLever_Down	752
-- iCommandViewNormalMouse	323
-- iCommandHelicopter_SelectWeapon_ALL	826
-- iCommand_FireExting_RightEngineExting	923
-- iCommandPlaneNightVisionLTSTCP	1194
-- iCommandPlaneNav_Targets	475
-- iCommandPlaneCDU_FPM	1240
-- iCommandSelecterUpRight	226
-- iCommandPlaneThrustRightDelta	2018
-- iCommandPlaneSelecterVertical	2032
-- iCommandViewCameraLeft	41
-- iCommandPlane_ADF_Volume_up	586
-- iCommandHelicopter_Engine_Launch_method	817
-- iCommandPlaneIntercomINTPress	1163
-- iCommandPlane_SpotLight_down	514
-- iCommandPlaneCDU_9	1250
-- iCommandPlaneIntercomVolumeDecrease	1185
-- iCommandPlaneIntercomTCNPress	1184
-- iCommandPlaneIntercomTCNIncrease	1183
-- iCommandExtLadderRelease	1540
-- iCommandHelicopter_PPR_button_K_up	301
-- iCommandPlane_R_828_volume_up	626
-- iCommandPlaneIntercomIFFDecrease	1176
-- iCommandViewCameraLeftSlow	45
-- iCommandPlaneIntercomAIMIncrease	1174
-- iCommandPlaneWheelBrakeLeftOff	962
-- iCommandPlaneCDU_Z	1279
-- iCommandPlane_R_800_2nd_wheel_down	610
-- iCommandPlaneRightMFD_OSB6	677
-- iCommandViewAWACSTargetChangeRadius	2135
-- iCommandADI_Test	773
-- iCommand_CPT_MECH_VMG_HYDRO_EKRAN	892
-- iCommandViewVerticalAbs	2011
-- iCommandPlaneIntercomHF	1191
-- iCommandPlaneIntercomVHFIncrease	1168
-- iCommandPlane_EngageGroundTargets	523
-- iCommandHelicopter_CollectiveStopper_Down	857
-- iCommandViewCockpit	7
-- iCommandPlaneIntercomFMDecrease	1164
-- iCommandPlaneCircuitBreaker_20	1134
-- iCommandPlaneSASTakeOffTrim	1160
-- iCommandViewPanToggle	346
-- iCommandPlaneSASMonitorTestLeft	1157
-- iCommandLampsControl	762
-- iCommandPlaneYawSASEngageL	1153
-- iCommandPlaneCircuitBreaker_38	1152
-- iCommandPlaneLeftMFD_OSB14_Off	995
-- iCommandPlaneHook	69
-- iCommandPlaneCircuitBreaker_37	1151
-- iCommandPlaneCDU_WP	1238
-- iCommandPlane_FLAPS_MNR_from_UP	1568
-- iCommandViewCameraUpLeftSlow	353
-- iCommandPlaneCircuitBreaker_29	1143
-- iCommandPlaneUHF0025MhzSelectorDec	1212
-- iCommandPlaneRightMFD_OSB4	675
-- iCommandViewAWACSLastZoomX2	2059
-- iCommandPlaneUFC_DEPR_UP	1320
-- iCommandPlaneLeftMFD_ADJ_Stop	1002
-- iCommandPlaneCircuitBreaker_19	1133
-- iCommandPlane_HOTAS_SpeedBrakeSwitchForward	577
-- iCommandPlaneCircuitBreaker_18	1132
-- iCommandPlaneCircuitBreaker_17	1131
-- iCommandPlaneCMSP_BRT_INC	1333
-- iCommandPlaneCircuitBreaker_14	1128
-- iCommandPlaneCircuitBreaker_11	1125
-- iCommandPlaneGearUp	430
-- iCommandPlaneCircuitBreaker_6	1120
-- iCommandPlaneCircuitBreaker_5	1119
-- iCommandPlaneLeftMFD_CON_Decrease	669
-- iCommandPlaneHUDFilterOnOff	247
-- iCommandPlaneCircuitBreaker_1	1115
-- iCommandPlaneEmerFlapsRetract	1113
-- iCommandPlane_Env_FlowLevel_Decrease	1520
-- iCommandPlaneEmerElevatorDisengageOff	1111
-- iCommandPlaneCMDChangeRippleQuantityOff	369
-- iCommandPlane_VHF_FM_Volume_Dec	1459
-- iCommandViewSnapView3	399
-- iCommandPlaneEmerTrimNoseUP	1105
-- iCommandPlaneRightMFD_SYM_Up	700
-- iCommandPlaneCollectiveIncrease	631
-- iCommandPlaneEmerTrimNeutral	1106
-- iCommandPlaneEmerSpeedBrakeRetract	1100
-- iCommandViewAWACSDistanceToolAngle	2055
-- iCommandViewCockpitSetGunnerSeat1	1605
-- iCommandPlaneFSQuantityIndicatorSelectorWING	1094
-- iCommandPlane_VHF_AM_FreqMode_OFF	1487
-- iCommandViewPlus	22
-- iCommandPlaneAHCPAltSCEBaro	1384
-- iCommandPlaneFSRightWingFillDisable	1086
-- iCommandPlaneFSLeftWingFillDisable	1085
-- iCommandPlaneFSRightWingBoostPump	1084
-- iCommandViewAWACSOutOfFocus	437
-- iCommandPlaneFSTankCrossFeed	1082
-- iCommandViewSnapView8	404
-- iCommandPlaneFSTankGate	1081
-- iCommandPlaneRightMFD_OSB19	690
-- iCommandPlaneCMSP_JMR_ON	1337
-- iCommandPlaneFSExtTanksFuselageValve	1078
-- iCommandViewBtn3Down	1599
-- iCommandFinishTrack	260
-- iCommandPlaneDownStop	196
-- iCommandPlaneLeftMFD_ADJ_Increase	662
-- iCommandPlane_WeaponMode_switch	533
-- iCommandElectricalPowerInverterSTBY	1074
-- iCommandHelicopter_SelectWeapon_vert_up	382
-- iCommandPlanePitchDelta	2013
-- iCommandEmergencyFlood	1072
-- iCommand_IlluminationInterf_Control_Panel_Illumination_brightness_up	942
-- iCommandPlaneTrimUp	95
-- iCommandViewTargets	151
-- iCommandAPUGeneratorPower	1071
-- iCommandPlaneQuickPadlockOn	1067
-- iCommandHelicopter_SignalFlares_switch_OnOff	828
-- iCommandViewSpeedUp	159
-- iCommandPlaneRadarDownRight	232
-- iCommandPlane_R_ENG_FUEL_FLOW_Override	1066
-- iCommandPlane_R_ENG_FUEL_FLOW_Norm	1065
-- iCommandPlane_L_ENG_FUEL_FLOW_Norm	1063
-- iCommandPlaneRightMFD_OSB20_Off	1026
-- iCommandPlane_R_ENG_OPER_Motor	1062
-- iCommandPlaneUHF100MhzSelector2	1202
-- iCommandPlane_L_ENG_OPER_Ign	1057
-- iCommandRightEngineStart	312
-- iCommandViewNavy	13
-- iCommandPlane_LG_WRN_Silence	1054
-- iCommandPlane_RDR_ALTM_DIS	1053
-- iCommandPlaneRightMFD_OSB14	685
-- iCommandPlaneEmerAileronDisengageOff	1108
-- iCommandGunFire	6
-- iCommandPlaneNav_THeadingTimeRangeF	482
-- iCommandHUDBrightnessDown	747
-- iCommandPlaneLaserRangerOnOff	392
-- iCommandViewCameraDown	44
-- iCommandViewAWACSTargetStartTime	2084
-- iCommand_AGR_Power	889
-- iCommandPlaneRightStart	199
-- iCommandPlaneCancelWeaponsDelivery	378
-- iCommandPlane_FLAPS_UP	1047
-- iCommandPlaneModeCannon	113
-- iCommandViewJFO	1043
-- iCommandHelicopter_SignalFlares_WHITE	831
-- iCommandPlane_HOTAS_CMS_Zaxis_Off	1042
-- iCommandThrottle2Stop	1040
-- iCommandPlaneUp	187
-- iCommandThrottle1Stop	1037
-- iCommandPlaneCDU_BLANC_R	1292
-- iCommandViewForward	37
-- iCommandFreezeActionSystem	293
-- iCommandViewAWACSDistanceY1	2071
-- iCommandThrottleStop	1034
-- iCommandThrottleDecrease	1033
-- iCommandPlaneStabTangBank	386
-- iCommandPlaneRightMFD_CON_Stop	1030
-- iCommandPlaneRightMFD_OSB8	679
-- iCommandPlane_ABRIS_Axis_Push_up	812
-- iCommandPlaneCMDChangeRippleIntervalOff	371
-- iCommandPlaneModeHelmet	109
-- iCommandPlaneLeftStart	197
-- iCommandAllMissilePadlock	259
-- iCommandPlaneRightMFD_OSB19_Off	1025
-- iCommandPlaneLeftStop	198
-- iCommandPlane_HOTAS_MasterModeControlButtonUP	633
-- iCommandViewPitCameraMoveUp	484
-- iCommandPlaneEmerAileronDisengageL	1107
-- iCommandPlaneDLK_All	451
-- iCommandViewCameraJiggle	299
-- iCommandPlaneRightMFD_OSB7_Off	1013
-- iCommandPlaneNav_Targets_off	874
-- iCommandPlaneRightMFD_OSB16_Off	1022
-- iCommandPlaneRadarStop	235
-- iCommandAltimeterPressureDecrease	317
-- iCommandPlaneRightMFD_OSB15_Off	1021
-- iCommandDebugAxis1	2088
-- iCommandViewStatic	150
-- iCommandPlaneRightMFD_OSB13_Off	1019
-- iCommandPlane_ABRIS_Brightness_Decrease	505
-- iCommandPlane_HOTAS_ChinaHatOff	589
-- iCommandViewSnapView2	398
-- iCommandPlaneNav_PB4	463
-- iCommandPlaneLeftMFD_BRT_Increase	666
-- iCommandViewLocal	190
-- iCommandPlaneDLK_Wingman1_up	784
-- iCommandViewGroundAndPlane	133
-- iCommandPlaneDLK_Wingman3	449
-- iCommandPlaneThrustCommonDelta	2016
-- iCommandPlane_VHF_AM_Squelch	1490
-- iCommandPlane_HOTAS_TriggerFirstStage_Off	639
-- iCommand_EjectInterface_Circuit_SelectRight	951
-- iCommandPlane_HOTAS_DataManagementSwitchUp	549
-- iCommandPlaneRightMFD_OSB3_Off	1009
-- iCommandMainHydraulicsCover	737
-- iCommandPlaneWingtipSmokeOnOff	78
-- iCommandPlaneRightMFD_OSB2_Off	1008
-- iCommandPlaneAUTIncreaseLeft	161
-- iCommandMarkerStateShip	266
-- iCommandAutoLockOnPreviousSurfaceTarget	279
-- iCommandPlane_HOTAS_NoseWheelSteeringButtonOff	606
-- iCommandPlane_GroundMovingTarget_up	796
-- iCommandPlaneEmerElevatorDisengageR	1112
-- iCommandPlaneLeftMFD_DSP_Increase	664
-- iCommandPlaneLeftMFD_CON_Stop	1005
-- iCommand_VMS_ALMAZ_UP_EmergencyOn	913
-- iCommandPlaneLeftMFD_DSP_Stop	1003
-- iCommandMouseViewOnOff	339
-- iCommandPlaneRightMFD_OSB5_Off	1011
-- iCommandMechClock_LeftLever_Up	754
-- iCommandViewSaveAngles9	244
-- iCommandPlaneLeftMFD_OSB20_Off	1001
-- iCommandPlaneCDU_E	1258
-- iCommand_PVI_BRIGHTNESS_LEVER_up	919
-- iCommandSelecterUp	141
-- iCommandPlane_RDR_ALTM_NRM	1052
-- iCommandGFire	1574
-- iCommandPlaneNav_DLK_OnOff	458
-- iCommand_FireExting_APUExting	922
-- iCommandCockpitSecondClickOff	434
-- iCommandMechClock_RightLever_Down	757
-- iCommandPlaneLeftMFD_OSB17_Off	998
-- iCommandPlaneNav_Enter_off	875
-- iCommandViewCameraUpRight	343
-- iCommandPlaneLeftMFD_OSB16_Off	997
-- iCommandViewSmoke1	1044
-- iCommandPlane_ABRIS_BT_3	498
-- iCommandPlaneLeftMFD_OSB13_Off	994
-- iCommandPlane_Env_WindshieldRainRemove	1512
-- iCommandMarkerStatePlane	264
-- iCommandPlaneLeftMFD_OSB10_Off	991
-- iCommandEngineLaunchMethod	838
-- iCommandViewCameraMoveMode	340
-- iCommandHelicopter_Left_Engine_Lock	600
-- iCommandViewCameraUp	43
-- iCommandPlaneLeftMFD_OSB9_Off	990
-- iCommandPointOfViewUp	216
-- iCommandPlaneNav_PB2	461
-- iCommandOneFrame	54
-- iCommandPlaneCMDShowAmountOrProgram	377
-- iCommandPlaneRotorTipLights	516
-- iCommandAWACSDeclare	270
-- iCommandPlaneCMDChangeBurstAmountOff	373
-- iCommandHelicopter_PPR_button_T_up	303
-- iCommandViewVertStop	296
-- iCommandPlaneIntercomIFFIncrease	1177
-- iCommand_SHKVAL_windscreen_wiper	918
-- iCommandPlane_VHF_AM_1MHz_Dec	1497
-- iCommandViewUpRight	205
-- iCommandPlaneNav_INU_realign	470
-- iCommandPlaneRightMFD_OSB10_Off	1016
-- iCommandPlane_HARS_Fast_Erect	1410
-- iCommandPlaneModeGrid	112
-- iCommandPlaneLeftMFD_OSB2_Off	983
-- iCommandViewChaseArcade	383
-- iCommandPlaneNMSP_EGI	1400
-- ICommandMenuItem12	977
-- iCommandViewSnapView0	396
-- iCommandViewLeftSlow	32
-- iCommandBrightnessILS	156
-- iCommandViewSnapView1	397
-- iCommandViewForwardSlowStop	289
-- iCommandPlaneCDU_J	1263
-- iCommandPlaneIntercomVHF	1189
-- iCommandViewObjectsAll	183
-- iCommandPlaneIntercomINT	1188
-- iCommandPlaneCMSP_RWR_ON	1339
-- iCommandPlaneRightMFD_OSB20	691
-- iCommandPlaneJettisonWeaponsUp	171
-- ICommandMenuItem6	971
-- iCommandLeftEngineStart	311
-- iCommandPointOfViewDownLeft	221
-- iCommand_LASTE_from_ALT_to_ALTHDG	1563
-- iCommandViewPitHeadOnOff	492
-- iCommandRotorRPMHigh_up	801
-- iCommandPointOfViewUpRight	217
-- iCommandPlaneWheelBrakeRightOn	963
-- iCommandPlaneNav_PB3	462
-- iCommandViewCaptainBridge	132
-- iCommandPlaneNav_POS_init	478
-- iCommandPlaneLeftMFD_OSB11	652
-- iCommandRALT_Test_up	779
-- iCommandViewUp	30
-- iCommandPlaneWheelBrakeLeftOn	961
-- iCommandPlaneEmergencyBrake	960
-- iCommandPlaneUHFFunctionDialADF	1221
-- iCommandAWACSBanditBearing	269
-- iCommand_FireDetectorsTest3rdGroup	956
-- iCommandBrakeGo	52
-- iCommandCompassRose	435
-- iCommandMissionRestart	1636
-- iCommandPlaneDropSnar	77
-- iCommandPlane_R_800_Noise_Reductor_on_off	615
-- iCommandPlaneNightTVOnOff	393
-- iCommandPlaneZoomOut	104
-- iCommandViewIRPointerOnOff	415
-- iCommandViewSaveAngles5	240
-- iCommandFuelBypassValve	728
-- iCommand_CPT_MECH_PitotSystemHeatTest	953
-- iCommand_ZMS_3_MagVarRotaryLeft	950
-- iCommandHelicopterLeftEngineBrake_ByAxis	2098
-- iCommandPlaneLeftMFD_OSB5_Off	986
-- iCommandDecreaseRadarScanArea	262
-- iCommandPlaneCMDChangeBoard	376
-- iCommandPlaneSAUHBarometric	59
-- iCommandViewSaveAngles8	243
-- iCommand_NAVINTERF_HeadingCourse	944
-- iCommandPlaneDLK_Self_ID_change	640
-- iCommand_EjectInterface_Circuit_SelectLeft	952
-- iCommand_IlluminationInterf_Control_Panel_Illumination_brightness_down	943
-- iCommandViewBack	38
-- iCommandMarkerStateRocket	265
-- iCommandViewCenter	36
-- iCommand_IlluminationInterf_Cockpit_Night_Illumination_brightness_up	936
-- iCommandPlaneRight	189
-- iCommand_AGR_axis_left	934
-- iCommandViewCameraDownLeftSlow	355
-- iCommandPlane_VHF_FM_FreqMode_DN	1467
-- iCommandHelicopter_PPR_button_H	591
-- iCommand_IlluminationInterf_Cockpit_Illumination	930
-- iCommandViewLock	19
-- iCommand_FireExting_VentilatorExting	924
-- iCommandPlane_ADF_Receiver_Mode_change	585
-- iCommand_FireExting_LeftEngineExting	921
-- iCommandPlane_HOTAS_BoatSwitchAft	564
-- iOculusRiftRoll	2146
-- iCommandPlaneLeftMFD_OSB5	646
-- iCommandPlaneLGPDownlockOverride	1395
-- iCommandPlaneWheelBrakeOff	75
-- iCommand_SHKVAL_scan_vel_up	916
-- iCommandElectronicControlSystemRightEngineCover	744
-- iCommandPlane_SPU9_radio_change	630
-- iCommandHelicopter_PanelsIlluminationButtonUp	834
-- iCommandViewAWACSInfoDelTargetButton	2141
-- iCommandPlaneRightMFD_OSB9	680
-- iCommandPlane_WeaponMode_Manual_Auto	532
-- iCommandPitotRam	911
-- iCommandPlane_ABRIS_BT_3_up	807
-- iCommandPlaneCircuitBreaker_4	1118
-- iCommandPlaneIntercomAIMPress	1175
-- iCommandPlaneDLK_Ingress	453
-- iCommandAccelReset	884
-- iCommandSeatArmHandle	1533
-- iCommand_EjectInterface_Circuit_Test	903
-- iCommandPlaneBettyRepeat	254
-- iCommandPlaneGearDown	431
-- iCommandAutoLockOnClear	384
-- iCommandPlaneCDU_LSK_9R	1235
-- iCommandPlaneRadarUp	90
-- iCommandPlaneRightMFD_BRTMODE_NIGHT	1531
-- iCommandPlaneAirBrake	73
-- iCommandEnginesStart	309
-- iCommandPlaneLeftMFD_DSP_Decrease	665
-- iCommandViewTower	9
-- iCommandGroundPowerDC_Cover	705
-- iCommandLaserRangeReset	888
-- iCommandPlaneTrimCancel	97
-- iCommandExtCargoHook	1633
-- iCommandRollForward	251
-- iCommandPlaneDesignate_CageOff	440
-- iCommandPlaneNav_THeadingTimeRangeF_off	881
-- iCommandViewIR	425
-- iCommandPlaneUFC_STEER_DOWN	1315
-- iCommandChangeRippleInterval	282
-- iCommandPlaneSASMonitorTestOff	1158
-- iCommandRefusalTWS	143
-- iCommandPlaneNav_POS_init_off	877
-- iCommandViewWeapons	149
-- iCommandPlaneNav_INU_normal_align_off	873
-- iCommandPlaneCDU_BLANC_L	1291
-- iCommandPlaneRefuelStatusIndLTSIncrease	1193
-- iCommandViewLaserOnOff	411
-- iCommandPlaneNav_PB1_off	859
-- ICommandMenuItem5	970
-- iCommandPlaneRightMFD_OSB_OFF	703
-- iCommandSwitchMasterArm	283
-- iCommandPlane_HOTAS_TargetManagementSwitchOff	548
-- iCommandPlaneIntercomVHFDecrease	1167
-- iCommandPlane_VHF_AM_Mode_PRE	1486
-- iCommandViewSwitchForward	181
-- iCommandAWACSTankerBearing	268
-- iCommandPlane_AmmoTypeSelect	534
-- iCommandPlaneVOID_2	1281
-- iCommandPlaneSalvoOnOff	81
-- iCommandEasyRadarScaleOut	837
-- iCommandPlane_LaserCode_Next	847
-- iCommandPlaneNav_PB9	468
-- iCommandPlane_I251_Brightness_Down	843
-- iCommandAutoLockOnPreviousAircraft	275
-- iCommandPlaneRadarDownLeft	233
-- iCommandViewPitCameraMoveBack	489
-- iCommandPlane_Helmet_Brightess_Down	841
-- iCommandPlaneCollectiveStop	839
-- iCommandPlaneChangeTarget	102
-- iCommandLandDetailsIncrease	137
-- iCommandEasyRadarScaleUp	836
-- iCommandHelicopter_PanelsIlluminationButtonDown	833
-- iCommandPlaneStopBase_Distance	414
-- iCommandPlaneLeftMFD_OSB_OFF	702
-- iCommandHelicopter_SelectWeapon_AA	827
-- iCommandHelicopter_Engine_Temperature_Control_Cover	823
-- iCommandPlaneCMDCancelCurrentProgram	374
-- iCommandSoundMicOn	123
-- iCommandViewStopSlow	214
-- iCommandHelicopter_TC_RPM_Cover	821
-- iCommandViewObjectIgnore	182
-- iCommandPlaneDLK_None_up	946
-- iCommandViewHorTrans	2048
-- iCommandChat	57
-- iCommandPlane_HOTAS_CoolieUp	539
-- iCommandPlaneUFC_ALT	1312
-- iCommandPlane_TACAN_Chanel_Ones_Decrease	1432
-- iCommandPlaneNav_PB0	459
-- iCommandPlaneAirBrakeOff	148
-- iCommandPlaneRightMFD_OSB17	688
-- iCommandChangeRWRMode	286
-- iCommandPlaneNav_BearingRangeT	483
-- iCommandSelecterDownRight	227
-- iCommandPlaneScalesReject	253
-- iCommandPlane_ABRIS_BT_5_up	809
-- iCommandPlaneAUTIncreaseRegimeLeft	165
-- iCommandHelicopter_Selected_Engine_start_up	802
-- iCommandActiveIRJamming	391
-- iCommandPlane_HOTAS_SpeedBrakeSwitchAft	578
-- iCommandPlane_AAP_PageSel_WAYPT	1419
-- iCommandPlane_AirborneTarget_up	797
-- iCommandGChangeSpeedH	1578
-- iCommandSelecterRight	140
-- iCommandPlaneRadarChangeMode	285
-- iCommandPlaneEOSOnOff	87
-- iCommandPlaneNav_SelfCoord_off	878
-- iCommandFuelPumpsTankRear	718
-- iCommandPlaneFlapsOn	145
-- iCommandPlaneAutopilotOverrideOff	428
-- iCommandPlaneParachute	76
-- iCommandPlane_VHF_FM_Preset_Inc	1472
-- iCommandRALT_DangerousAltitudeRotaryRight	777
-- iCommandADI_ZeroPitchTrimRight	772
-- iCommandHelicopter_PPR_button_B	593
-- iCommandPlane_R_828_Noise_Reductor_on_off	624
-- iCommandMechClock_LeftLever_TurnLeft	755
-- iCommandMechClock_RightLever_Rotate_left	759
-- iCommandPointOfViewStop	225
-- iCommandPlaneLeftMFD_OSB16	657
-- iCommandPlaneLeft	188
-- iCommandRightEngineStop	314
-- iCommandPlaneEmerAileronDisengageR	1109
-- iCommandEjectingSystemPower2	732
-- iCommandPointOfViewCenter	224
-- iCommandViewKeepTerrain	395
-- iCommandRollbackSave	249
-- iCommandPowerBattery2_Cover	709
-- iCommandPlaneEmergencyDisconnectLever	965
-- iCommandPlaneUHF0025MhzSelectorInc	1211
-- iCommandDebriefing	1537
-- iCommandViewUpSlow	34
-- iCommandMechClock_LeftLever_Down_up	753
-- iCommandCockpitCursorHorizontal	2036
-- iCommandPlane_ABRIS_Brightness_Increase	504
-- iCommandPlaneHeadLightOnOff	328
-- iCommandViewSnapView9	405
-- iCommandPlaneSAUAutomatic	58
-- iCommandPlaneTrimRight	94
-- iCommandSelecterLeft	139
-- iCommandMissionResourcesManagement	1560
-- iCommandPlaneLeftMFD_OSB8	649
-- iCommandPlanePickleOn	350
-- iCommandPlaneNav_Wind	481
-- iCommandPlaneCMDCancelCurrentProgramOff	375
-- iCommandPlaneFireOff	85
-- iCommandPlaneAUTDecrease	65
-- iCommandHelicopter_Right_Engine_Lock	601
-- iCommandPlaneAUTDecreaseRegimeLeft	166
-- iCommandPlane_ADF_Test_up	792
-- iCommandPlaneRadarCenter	92
-- iCommandHelicopter_Engine_Select	599
-- iCommandPlane_VHF_FM_Mode_EMERFM	1461
-- iCommandPlane_HOTAS_MIC_SwitchLeft	574
-- iCommandPlane_HOTAS_PinkySwitchForward	568
-- iCommandPlane_VHF_AM_Mode_MAN	1485
-- iCommandViewExternalZoomDefault	338
-- iCommandViewCoordinatesInLinearUnits	245
-- iCommandViewPitCameraMoveRight	487
-- iCommandPlane_HOTAS_BoatSwitchForward	563
-- iCommandPlaneDesignate_CageOn_horizontal	442
-- iCommandPlane_HOTAS_DataManagementSwitchLeft	551
-- iCommandSlaveToTanker	1610
-- iCommand_FireDetectorsTest2ndGroup	955
-- iCommandViewNormalKeyboard	333
-- iCommandPlane_HOTAS_TargetManagementSwitchDown	545
-- iCommandReloadTables	849
-- iCommandPlaneIntercomFM	1190
-- iCommandRecordSubtitleOn	324
-- iCommand_IlluminationInterf_Panels_Illumination_brightness_up	938
-- iCommandPlaneUpStop	194
-- iCommandPlaneCircuitBreaker_21	1135
-- iCommandPlaneLeftMFD_OSB6_Off	987
-- iCommandInfoDataOnOff	154
-- iCommandHelicopter_PPR_button_B_up	304
-- iCommandPlaneNav_INU_precise_align	472
-- iCommandAPUFuelValveShutOff	726
-- iCommandPlaneCockpitIlluminationGauges	494
-- iCommandPlaneRadarUpRight	231
-- iCommandRotatePlus	1
-- iCommandMarkerState	261

